### ISSUE TITLE
`@Prop() tag: string[]` get coerced to `[string][]`, making validation always fail

### ISSUE THREAD

**Issue by patarapolw** [typegoose/typegoose#321] opened 2020-07-13 06:11 UTC
## Versions

- NodeJS: 12.16.3
- Typegoose(NPM): 7.2.0
- mongoose: 5.9.20
- mongodb: 3.5.9

## What is the Problem?

Indeed, this throws no error,

```ts
// Payload: tag: ['template', 'zhquiz']
@Prop() tag?: string[]
```

but `string[]` get coerced to `[string][]` inside the database. This can be proved via

```ts
@Prop({ validate: (s: string[]) => {
  console.log(s)
  return s.every(s0 => typeof s0 === 'string')
} }) tag?: string[]
```

I see this in the console.

```json
[["template"],["zhquiz"]]
```

And, yes, this always fail.

## Temporary solution

```ts
@prop({ type: Schema.Types.Mixed }) tag?: string[]
// Or
@prop({ type: Schema.Types.Mixed }) tag: string[]
```

To be extra sure, I make it like this,

```ts
  @prop({
    type: Schema.Types.Mixed,
    validate: (s: string[] = []) => s.every((s0) => typeof s0 === 'string'),
  })
  tag?: string[]
// Or
  @prop({
    required: true,
    type: Schema.Types.Mixed,
    validate: (s: string[] = []) => s.every((s0) => typeof s0 === 'string'),
  })
  tag: string[]
```

## Do you know *why* it happens?

*no*

**Comment by jamesmillerburgess** [comment] 2020-07-13 08:56
We found the same thing.

Here is a unit test that reproduces the issue:
![스크린샷 2020-07-13 오전 11 27 02](https://user-images.githubusercontent.com/15968012/87279513-e1f5b380-c4fc-11ea-938c-484e7bcaab75.png)

And here is where I think the extra array is being added:
![스크린샷 2020-07-13 오후 12 01 22](https://user-images.githubusercontent.com/15968012/87285114-2dfa2580-c508-11ea-83a6-aeff18167d17.png)

**Comment by jamesmillerburgess** [comment] 2020-07-13 09:34
It looks like `Type` gets correctly overridden to `String` when it is present in the decorator options, but remains as `Array` when not present:

![스크린샷 2020-07-13 오후 1 30 11](https://user-images.githubusercontent.com/15968012/87288981-1ffad380-c50d-11ea-8d8e-a7046b566b1a.png)

This leads to the mongoose type being resolved incorrectly to `SchemaArray` instead of `SchemaString` here in `mapOptions`:
![스크린샷 2020-07-13 오후 1 32 56](https://user-images.githubusercontent.com/15968012/87289276-7bc55c80-c50d-11ea-9e14-849e4d56ba24.png)

**Comment by hasezoey** [comment] 2020-07-13 11:38
Duplicate of #300 and #318

**Closed by hasezoey** 2020-07-13 11:38 UTC
Labels: bug

**Comment by jamesmillerburgess** [comment] 2020-07-13 12:06
I see - maybe we can make this clearer in the documentation, where it looks like the `type` property is only necessary for special cases. 

This would avoid others reporting this same issue after spending time debugging something that was intended behavior.
