### ISSUE TITLE
Mongoose 7 update?

### ISSUE THREAD

**Issue by max-prtsr** [typegoose/typegoose#804] opened 2023-03-25 02:57 UTC
## Describe what you need | want

I want mongoose 7 :)

## Do you have already an idea for the implementation?

https://mongoosejs.com/docs/migrating_to_7.html

**Comment by smolinari** [comment] 2023-03-25 04:59
https://github.com/typegoose/typegoose/releases/tag/v11.0.0-beta.1

Version 11 is at beta 2. Release date of the GA version is targeted for Monday the 27th. 

Scott

**Comment by hasezoey** [comment] 2023-03-25 08:47
Duplicate of #795

**Closed by hasezoey** 2023-03-25 08:47 UTC
Labels: feature

**Comment by max-prtsr** [comment] 2023-03-29 06:43
@hasezoey just a small note that usually people search issues about compatbility and upgrades, not discussion.
