### ISSUE TITLE
Expression produces a union type that is too complex to represent

### ISSUE THREAD

**Issue by tar-aldev** [typegoose/typegoose#563] opened 2021-06-18 10:51 UTC
## Versions

- System: linux
- NodeJS: 14.16.0
- Typescript: 4.3.2
- Typegoose(NPM): ^7.6.0 
- mongoose: <=5.10.18
- mongodb: ^3.6.9
"@types/mongoose": "<=5.10.5",

## What is the Problem?
Calling .create() on model gives an error:
```
error TS2590: Expression produces a union type that is too complex to represent.
```
It happens only in CI for some reason.

## Code Example
The code is quite simple, so I don't think it is connected with our typedefinitions
```ts
// agreement type is defined as
AgreementFromForm & {
      ownerId: Types.ObjectId;
      createdBy: Agreement['createdBy'];
      createdAt: Agreement['createdAt'];
}

this.agreementModel.create({ // <- errors here
      _id: new Types.ObjectId(),
      ...agreement
});
```

```ts
code here
```

## Do you know *why* it happens?

*no*

---

**Comment by hasezoey** [comment] 2021-06-18 10:54
Duplicate of #499

**Comment by hasezoey** [comment] 2021-06-18 10:56
is there an full reproduction code?

and did you already try an higher/lower typescript version?

**Comment by hasezoey** [comment] 2021-09-16 11:32
closing, because duplicate of #499

**Closed by hasezoey** 2021-09-16 11:32 UTC
Labels: bug
