### ISSUE TITLE
Upgrading from 6.1.0-9 to 6.1.0-10 or greater errors with Assertion `(current_write_) == nullptr' failed

### ISSUE THREAD

**Issue by JakeAi** [typegoose/typegoose#127] opened 2019-11-18 14:23 UTC
## Versions

- NodeJS: 12.13.0
- Typegoose(NPM): 6.1.0-10 
- Typegoose(GIT): commithash
- mongoose: 5.7.11
- mongodb: 3.3.3

## What is the Problem?
Going from 6.1.0-9 to anything greater errors with ``Assertion `(current_write_) == nullptr' failed``

## Code Example

```
[2019-11-18 09:12:34] [INFO] testApp connected
[2019-11-18 09:12:34] [INFO] testApp database ready
[2019-11-18 09:12:34] [INFO] testSite connected
[2019-11-18 09:12:34] [INFO] testSite database ready
[2019-11-18 09:12:34] [INFO] Creating App
[2019-11-18 09:12:34] [INFO] Created App
[2019-11-18 09:12:34] [INFO] Using port 4000
[2019-11-18 09:12:34] [INFO] Creating Server
[2019-11-18 09:12:34] [INFO] Created Server
[2019-11-18 09:12:34] [INFO] Running server on port 4000 running under false
(node:2672) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
ng serve mm-api[2672]: c:\ws\src\tls_wrap.cc:730: Assertion `(current_write_) == nullptr' failed.
 1: 00007FF7F661094F napi_wrap+124431
 2: 00007FF7F65B2696 v8::base::CPU::has_sse+34502
 3: 00007FF7F65B29B3 v8::base::CPU::has_sse+35299
 4: 00007FF7F64CB344 std::basic_ostream<char,std::char_traits<char> >::put+18948
 5: 00007FF7F64CE26E uv_loop_size+2894
 6: 00007FF7F652F895 v8::internal::LookupIterator::index+22229
 7: 00007FF7F652C510 v8::internal::LookupIterator::index+9040
 8: 00007FF7F6D6B150 v8::internal::Builtins::builtin_handle+325536
 9: 00007FF7F6D6A697 v8::internal::Builtins::builtin_handle+322791
11: 00007FF7F6D6A7DE v8::internal::Builtins::builtin_handle+323118
12: 00007FF7F71E2D6D v8::internal::SetupIsolateDelegate::SetupHeap+568205
13: 00007FF7F71627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
14: 00007FF7F71627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
15: 00007FF7F71627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
16: 00007FF7F71627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
17: 00007FF7F71627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
18: 00007FF7F71627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
19: 00007FF7F71627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
20: 00007FF7F71627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
21: 00007FF7F71627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
22: 00007FF7F71627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
23: 00007FF7F71627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
24: 00007FF7F715FDB1 v8::internal::SetupIsolateDelegate::SetupHeap+31697
25: 00007FF7F715F99C v8::internal::SetupIsolateDelegate::SetupHeap+30652
26: 00007FF7F6CC4F43 v8::internal::Execution::CallWasm+1395
27: 00007FF7F6CC48C6 v8::internal::Execution::Call+182
28: 00007FF7F6D95B3B v8::Function::Call+603
29: 00007FF7F662C79D node::CallbackScope::~CallbackScope+749
30: 00007FF7F662CA61 node::CallbackScope::~CallbackScope+1457
31: 00007FF7F6625FE3 v8::internal::interpreter::BytecodeNode::operand_scale+179
32: 00007FF7F652EC00 v8::internal::LookupIterator::index+19008
33: 00007FF7F652F3FC v8::internal::LookupIterator::index+21052
34: 00007FF7F64CA5E2 std::basic_ostream<char,std::char_traits<char> >::put+15522
35: 00007FF7F64CAA08 std::basic_ostream<char,std::char_traits<char> >::put+16584
36: 00007FF7F64CCE73 std::basic_ostream<char,std::char_traits<char> >::put+25907
37: 00007FF7F652A605 v8::internal::LookupIterator::index+1093
38: 00007FF7F66441FB uv_tty_set_mode+9659
39: 00007FF7F66590DC uv_loop_init+844
40: 00007FF7F6659414 uv_run+244
41: 00007FF7F657B892 EVP_CIPHER_CTX_buf_noconst+30946
42: 00007FF7F65D9263 node::Start+275
43: 00007FF7F649666C RC4_options+339308
44: 00007FF7F7295D58 v8::internal::SetupIsolateDelegate::SetupHeap+1301368
45: 00007FFCDA9D7BD4 BaseThreadInitThunk+20
46: 00007FFCDB78CED1 RtlUserThreadStart+33
```

```ts
import { logger } from '@mm-mono/api/logger.handler';
import { IModelOptions } from '@typegoose/typegoose/lib/types';
import { Connection, ConnectionOptions, createConnection } from 'mongoose';

const options: ConnectionOptions = {
  keepAlive: true,
  useNewUrlParser: true,
  useFindAndModify: false,
  autoReconnect: true,
  reconnectInterval: 2000,
  reconnectTries: Number.MAX_VALUE,
  connectTimeoutMS: 30000,
  // @ts-ignore
  useUnifiedTopology: true
};


export const typegooseSchemaOptions = {
  _id: true,
  timestamps: true
};

export module testSiteMongoDb {
  export let testSite: Connection = null;
  testSite = createConnection(process.env.MONGODB_URI, options);

  testSite.on('error', (error) => {
    logger.error(error);
    logger.info(`testSite errored`);
  });
  testSite.on('open', () => logger.info(`testSite database ready`));
  testSite.on('connected', () => logger.info(`testSite connected`));
  testSite.on('disconnected', () => logger.info(`testSite disconnected`));


  export const testSiteOptions: IModelOptions = {
    existingConnection: testSiteMongoDb.testSite,
    schemaOptions: typegooseSchemaOptions
  };

  export function connectMongoDb() {
    return testSite;
  }
}


export module testAppMongoDb {
  export let testApp: Connection = null;
  testApp = createConnection(process.env.MONGODB_APP_URI, options);

  testApp.on('error', (error) => {
    logger.error(error);
    logger.info(`testApp errored`);
  });
  testApp.on('open', () => logger.info(`testApp database ready`));
  testApp.on('connected', () => logger.info(`testApp connected`));
  testApp.on('disconnected', () => logger.info(`testApp disconnected`));


  export const testAppOptions: IModelOptions = {
    existingConnection: testAppMongoDb.testApp,
    schemaOptions: typegooseSchemaOptions
  };

  export function connectMongoDb() {
    return testApp;
  }
}

```

## Do you know *why* it happenes?
no, dependency wise, semver and tslib were added. loglevel and reflect-metadata were updated.

**Comment by hasezoey** [comment] 2019-11-18 14:39
this dosnt seem like an typegoose issue - it is a NodeJS error, that i dont understand - could you give me typegoose debug log? `setLogLevel("DEBUG")` (preferably with gist / pastebin)

**Comment by hasezoey** [comment] 2019-11-18 14:42
addition:
could you try setting `createIndexes` to true? (connection options) and giving me the mongodb version you use?

**Comment by JakeAi** [comment] 2019-11-18 14:59
[https://pastebin.com/VFcR6hHH](https://pastebin.com/VFcR6hHH)
If I downgrade to 6.1.0-9 it works with no errors.

**Comment by hasezoey** [comment] 2019-11-18 15:04
i dont see anything suspicious in the logs

**Comment by Ben305** [comment] 2019-11-18 15:19
`ng serve mm-api[2672]: c:\ws\src\tls_wrap.cc:730: Assertion `(current_write_) == nullptr' failed.``

ng serve belongs to Angular? Is the error log output from Angular CLI?

**Comment by hasezoey** [comment] 2019-11-18 15:25
do you have an reproduce able example? - because i cant reproduce it

**Comment by hasezoey** [comment] 2019-11-18 15:26
and could you explain what `@mm-mono` is?

**Comment by JakeAi** [comment] 2019-11-18 15:28
I'm using https://github.com/nrwl/nx which revolves around angular but in the end, it runs node main.js. If I TSC build the project without anything angular and run it normally (node main.js) it errors the same way. But I may I figured it out... I think mongoose changed along the way with their Connection object and how I'm waiting for mongoose to connect before proceeding. I will close the issue if I am correct.

@mm-mono is my monorepo. It's part of NX

```json
  "paths": {
      "@mm-mono/errors": ["libs/errors/index.ts"],
      "@mm-mono/data-access": ["libs/data-access/index.ts"],
      "@mm-mono/endpoints": ["libs/endpoints/index.ts"],
      "@mm-mono/utilities/*": ["libs/utilities/*"],
      "@mm-mono/data": ["libs/data/index.ts"],
      "@mm-mono/sapbobscom": ["libs/sapbobscom/index.ts"],
      "@mm-mono/online-store": ["libs/online-store/index.ts"],
      "@mm-mono/common": ["libs/common/index.ts"],
      "@mm-mono/api/*": ["libs/api/*"],
      "@mm-mono/dashboard/*": ["libs/dashboard/*"],
      "@mm-mono/nativescript/*": ["libs/nativescript/*"],
      "@mm-mono/angular-modules/*": ["libs/angular-modules/*"],
      "@mm-mono/angular-validators": ["libs/angular-validators/index.ts"],
      "@mm-mono/angular-hooks/*": ["libs/angular-hooks/*"]
    }
```

**Comment by hasezoey** [comment] 2019-11-18 15:29
> paths

this is known to bring errors to typegoose - but i think not in this case

**Comment by hasezoey** [comment] 2019-11-18 15:34
>  I think mongoose changed along the way with their Connection

just to note, from version 6.1.0-9 to 6.1.0-10 (or even 6.1.2) mongoose requirement was not upgraded

---

i think this is not typegoose related, so i will close this one

**Closed by hasezoey** 2019-11-18 15:34 UTC
Labels: bug, cant reproduce, info needed

**Comment by JakeAi** [comment] 2019-11-18 19:18
No matter what I do, as soon as I upgrade past 6.1.0-9 to 6.1.0-10 or greater my app breaks. I'm using existingConnections on my modals. I've been using the same code base for over a year.

I updated to 6.1.0-10 and diffed the folders. Came across 

```JS
function mergeMetadata(key, value, cl) {
    if (typeof key !== 'string') {
        throw new TypeError(`"${key}"(key) is not a string! (assignMetadata)`);
    }
    if (typeof cl !== 'function') {
        throw new errors_1.NoValidClass(cl);
    }
    const current = Object.assign({}, Reflect.getMetadata(key, cl) || {});
    if (util_1.isNullOrUndefined(value)) {
        return current;
    }
    // the following checks are needed, so that the new value dosnt override the full options
    // "deepmerge" cannot be used because of the other options like "existingMongoose"
    if (isModelOptions(value) && !util_1.isNullOrUndefined(current.schemaOptions)) {
        value.schemaOptions = Object.assign(current.schemaOptions, value.schemaOptions);
    }
    if (isModelOptions(value) && !util_1.isNullOrUndefined(current.options)) {
        value.options = Object.assign(current.options, value.options);
    }
    return Object.assign(current, value);
}
exports.mergeMetadata = mergeMetadata;
```

vs
```JS
function mergeMetadata(key, value, cl) {
    if (typeof key !== 'string') {
        throw new TypeError(`"${key}"(key) is not a string! (assignMetadata)`);
    }
    if (typeof cl !== 'function') {
        throw new errors_1.NoValidClass(cl);
    }
    // Please dont remove the other values from the function, even when unused - it is made to be clear what is what
    const current = lodash_1.cloneDeepWith(Reflect.getMetadata(key, cl) || {}, (val, ckey, obj, stack) => customMerger(key, val));
    return lodash_1.mergeWith({}, current, value, (objValue, srcValue, ckey, object, source, stack) => customMerger(key, srcValue));
}
exports.mergeMetadata = mergeMetadata;
```

When I add that old function back in, everything works properly.

**Comment by hasezoey** [comment] 2019-11-18 19:33
could you try replacing the return with
```ts
return lodash_1.mergeWith({}, Reflect.getMetadata(key, cl), value, (objValue, srcValue, ckey, object, source, stack) => customMerger(key, srcValue));
```
and commenting out the `const current` line?

**Comment by JakeAi** [comment] 2019-11-18 19:33
@Ben305 @hasezoey 
Changing (in the util.js node module file on line 185)
```JS
const current = lodash_1.cloneDeepWith(Reflect.getMetadata(key, cl) || {}, (val, key, obj, stack) => customMerger(ckey, val));
return lodash_1.mergeWith({}, current, value, (objValue, srcValue, ckey, object, source, stack) => customMerger(key, srcValue));
```
to 
```JS
const current = lodash_1.cloneDeepWith(Reflect.getMetadata(key, cl) || {}, (val, ckey, obj, stack) => customMerger(ckey, val));
return lodash_1.mergeWith({}, current, value, (objValue, srcValue, ckey, object, source, stack) => customMerger(ckey, srcValue));
```
Works on the latest version. Because `key` in `custommerger` was always `typgeoose:options` while `ckey` seems to be the proper key to check for as it does contain existingConnection/mongoose.

**Comment by JakeAi** [comment] 2019-11-18 19:35
> could you try replacing the return with
> 
> ```ts
> return lodash_1.mergeWith({}, Reflect.getMetadata(key, cl), value, (objValue, srcValue, ckey, object, source, stack) => customMerger(key, srcValue));
> ```
> 
> and commenting out the `const current` line?

This also seems to work.

**Comment by hasezoey** [comment] 2019-11-18 19:35
wait, that worked?

**Comment by hasezoey** [comment] 2019-11-18 19:36
anyway - thanks for pointing out that i didnt use `ckey` - will be fixed in 6.1.5

as for the other thing - why did that work?

**Comment by JakeAi** [comment] 2019-11-18 19:40
> wait, that worked?

My "fix" and your fix worked for me on the latest version. Somehow this was the root of my original nodejs issue. Probably a bad clone? I'm not sure why yours is working but when I log the `key` parameter in customMerger, it was 
```
typegoose:options
typegoose:options
typegoose:options
typegoose:options
typegoose:options
typegoose:options
typegoose:options
typegoose:options
typegoose:options
typegoose:options
typegoose:options
typegoose:options
typegoose:options
typegoose:options
typegoose:options
typegoose:options
typegoose:options
typegoose:options
typegoose:options
typegoose:options
typegoose:options
typegoose:options
typegoose:options
typegoose:options
typegoose:options
typegoose:options
```

When I applied my fix of ckey, it was
```
_id
timestamps
existingConnection
options
allowMixed
schemaOptions
_id
timestamps
existingConnection
schemaOptions
_id
timestamps
existingConnection
schemaOptions
_id
timestamps
schemaOptions
_id
timestamps
options
allowMixed
schemaOptions
options
allowMixed
schemaOptions
options
allowMixed
schemaOptions
schemaOptions
_id
timestamps
```

**Comment by hasezoey** [comment] 2019-11-18 19:42
> I'm not sure why yours is working but when I log the key parameter in customMerger, it was

i have done this too, like i said, fixed in 6.1.5, i just need to know why my case worked (and if there are any drawbacks of not cloning first)

**Comment by JakeAi** [comment] 2019-11-18 19:45
Great! I'm glad this is resolved, thanks for taking the time to look into it with me.

**Comment by hasezoey** [comment] 2019-11-18 20:10
Thanks again for pointing this out - version 6.1.5 is now released with the fix

**Comment by JakeAi** [comment] 2019-11-18 20:19
> Thanks again for pointing this out - version 6.1.5 is now released with the fix

Works perfectly 😄  thanks!

**Comment by hasezoey** [comment] 2019-11-18 20:32
the error you provided was (and still is) very cryptic - and dosnt seem like it comes from typegoose, but in the end, it came from typegoose - thanks again for noticing this

**Comment by JakeAi** [comment] 2019-11-18 20:57
I spent probably 3 days trying to narrow down where it came from because I did a small npm update and audit. At first I thought it was mongoose.

**Comment by hasezoey** [comment] 2019-11-18 21:06
> I spent probably 3 days trying

sorry! (was my mistake not using `ckey` instead of `key`)
