### ISSUE TITLE
Conflict with mongoose 5.11.12 (latest in 2 days ago)

### ISSUE THREAD

**Issue by sm-hejazi** [typegoose/typegoose#479] opened 2021-01-20 13:55 UTC
```
node_modules/@typegoose/typegoose/lib/hooks.d.ts:8:41 - error TS2314: Generic type 'Query<ResultType, DocType>' requires 2 type argument(s).
8 declare type PreFnWithQuery<T> = (this: Query<T>, next: (error?: Error) => ReturnVoid, done: EmptyVoidFn) => ReturnVoid;
                                          ~~~~~~~~
node_modules/@typegoose/typegoose/lib/queryMethod.d.ts:1:15 - error TS2305: Module '"mongoose"' has no exported member 'DocumentQuery'.
1 import type { DocumentQuery } from 'mongoose';
                ~~~~~~~~~~~~~
node_modules/@typegoose/typegoose/lib/typegoose.d.ts:56:131 - error TS2344: Type 'U' does not satisfy the constraint 'Document<any>'.
  Type 'AnyParamConstructor<any>' is missing the following properties from type 'Document<any>': $ignore, $isDefault, $isDeleted, $isEmpty, and 45 more.
56 export declare function buildSchema<U extends AnyParamConstructor<any>>(cl: U, options?: mongoose.SchemaOptions): mongoose.Schema<U>;
                                                                                                                                     ~
node_modules/@typegoose/typegoose/lib/types.d.ts:19:55 - error TS2314: Generic type 'Model<T>' requires 1 type argument(s).
19 export declare type ModelType<T, QueryHelpers = {}> = mongoose.Model<DocumentType<T>, QueryHelpers>;
                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 4 errors.
```

**Comment by hasezoey** [comment] 2021-01-20 13:57
Duplicate of #432

**Closed by hasezoey** 2021-01-20 13:57 UTC
