### ISSUE TITLE
Support for Mongoose 5.12.7

### ISSUE THREAD

**Issue by alhassanv** [typegoose/typegoose#532] opened 2021-05-08 09:52 UTC
Will mongoose 5.12.7 be supported? 
I'm getting the notice `Using Unsupported mongoose version, highest supported is 5.10.18 (Current version: 5.12.7)`

**Comment by hasezoey** [comment] 2021-05-08 09:59
Duplicate of #432

**Closed by hasezoey** 2021-05-08 09:59 UTC
Labels: question
