### ISSUE TITLE
Typegoose + nestjs: index not creating using @index decorator

### ISSUE THREAD

**Issue by ragasave** [typegoose/typegoose#472] opened 2021-01-07 18:21 UTC
## Versions
- System: windows
- NodeJS: v12.18.3
- Typescript: 4.1.3
- Compiler / Transpiler: ts-node
- Typegoose(NPM): 7.4.6
- Typegoose(GIT): commithash
- mongoose: 5.11.9
- mongodb:4.2.11
- nestjs / nestjs-typegoose: 7.5.1 / 7.1.38

## What is the Problem?
Hii Guys,
I am facing an error with typegoose. I have a model called `SP` and i have to create 2dsphere index on its property called `geoLocation` i tried typegoose decorator `@index` but it is not working even its not throwing any error, i dont no what happing and how typegoose handle it.is there any one who give me the solution of it 👆.

## Code Example

```ts
import { Prop, index, modelOptions, Severity } from '@typegoose/typegoose';
import { BaseModel } from '../base.model';
import { Factory } from 'nestjs-seeder';

export enum SPStatus {
    INAVTIVE = "INAVTIVE",
    ACTIVE = "ACTIVE",
}

@modelOptions({ options: { allowMixed: Severity.ALLOW } })
@index({ geoLocation: '2dsphere' }, {})
export class SP extends BaseModel{
    @Factory(faker => faker.company.companyName())
    @Prop({ required: true, index: true, text: true })
    businessName : string
    
    @Factory(faker => {
        let data = {
            type : "Point",
            coordinates:[Number(faker.address.longitude()), Number(faker.address.latitude())]
        }
        console.log(data);

        return data;
    })
    @Prop({ required: false })
    geoLocation: {
        type: string,
        coordinates: [number]
    }
}
```

## Do you know *why* it happens?

*no*

---

**Comment by hasezoey** [comment] 2021-01-08 09:48
is this an duplicate of https://stackoverflow.com/questions/65617696/typegoose-nestjs-mongodb-index-not-creating-using-index-decorator ?

**Comment by hasezoey** [comment] 2021-01-08 09:50
anyway, i will repost it here:
- are you trying to add an index to an existing collection, or on an new collection? (if existing collection, did you already try `Model.syncIndexes`?)
- did you already try with the typegoose supported version of mongoose? [(highest supported is 5.10.18)](https://typegoose.github.io/typegoose/docs/guides/faq#why-is-74x-constrained-to-mongoose-51018)

**Closed** 2021-01-19 16:26 UTC
Labels: bug
