### ISSUE TITLE
Cannot use mongoose hidden on array of reference

### ISSUE THREAD

**Issue by benjaminb-** [typegoose/typegoose#397] opened 2020-10-05 06:41 UTC
## Versions

Using Typegoose 7.4.1

Hi, i'm not able to hide properties with mongoose-hidden plugin when the property is an array of references.
With a simple ref property, it's working.

I tried with mongoose directly and it's working. Is it a known bug / missing feature, how can I help more, to understand and propose a fix if necessary.

Thanks :)

## Code Example

```ts
  @IsMongoId()
  @prop({ hide: true }) // this prop is hidden
  public company: ObjectId;

  @IsArray()
  @prop({ ref: "Role", hide: true }) // this prop is NOT hidden, it should be
  public roles: Array<Role>;
```

## Do you know *why* it happens?

*no*

**Comment by benjaminb-** [comment] 2020-10-05 06:55
Using this "hack" i was able to make it work, i still don't understand

```
@prop({ ref: "Role", refType: Array,  hide: true })
private roles: Role; // TODO: FIXME using type not as an array the hide is working
```

**Comment by smolinari** [comment] 2020-10-05 07:19
Hi,

Can you try it out like this?

```
@prop({ ref: "Role", hide: true })
private roles?: Ref<Role>[];
```

Scott

**Comment by benjaminb-** [comment] 2020-10-05 08:06
> @prop({ ref: "Role", hide: true })
> private roles?: Ref<Role>[];

The hide feature is not working like that too

**Comment by smolinari** [comment] 2020-10-05 08:10
@benjaminb- That's not the code I specified. Did you try both?

Scott

**Comment by benjaminb-** [comment] 2020-10-05 08:12
i found when trying to parse the mongoose schema options generated by typegoose.

```
@prop({ ref: "Role", hide: true })
public roles: Array<Role>;

SchemaArrayOptions {
   type: [ { type: [Function], ref: 'Role', hide: true } ] 
}
```

```
@prop({ ref: "Role", hide: true })
public roles:  Role;

SchemaArrayOptions {
   type: [Function: Array],
   ref: 'Role',
   hide: true
}

```

And in the second case the hide plugin is working as the, "hide" options is at the right place,  in the first situation the "hide" option is not working

**Comment by benjaminb-** [comment] 2020-10-05 08:13
> @benjaminb- That's not the code I specified. Did you try both?
> 
> Scott

i tried you code sorry wrong copy paste, it's not working

**Comment by hasezoey** [comment] 2020-10-05 09:02
im unsure of what the problem is, but the correct(/recommened) usage would be
```ts
@prop({ ref: () => Class, hide: true })
public someReference?: Ref<Class>[];
```

if you still have an problem, please provide the full typegoose debug log

**Comment by benjaminb-** [comment] 2020-10-05 09:20
> im unsure of what the problem is, but the correct(/recommened) usage would be
> 
> ```ts
> @prop({ ref: () => Class, hide: true })
> public someReference?: Ref<Class>[];
> ```
> 
> if you still have an problem, please provide the full typegoose debug log

Doing that, it s not working

```
  @prop({ ref: () => Role, hide: true })
  public rolesTest?: Ref<Role>[];
```

But Doing that workaround, it s working

```
  @prop({ ref: () => Role, hide: true })
  public rolesTest?: Ref<Role>;
```

Like I said befaire, the "hide" option is set that way in mongoose schema option for rolesTest property 

```
SchemaArrayOptions {
   type: [ { type: [Function], ref: 'Role', hide: true } ] 
}
```

But in the second case (just removing the []) so it's not typed as array the schema options are like that, and this is working fine !

```
SchemaArrayOptions {
   type: [Function: Array],
   ref: 'Role',
   hide: true
}
```

and there is the full logs about this schema :

```
buildSchema called for "Group"
_buildSchema Called for AbstractModel with options: { id: false,
  timestamps: true,
  versionKey: false,
  toObject: { getters: true, virtuals: true },
  toJSON: { getters: true, virtuals: true } }
_buildSchema Called for Group with options: { id: false,
  timestamps: true,
  versionKey: false,
  toObject: { getters: true, virtuals: true },
  toJSON: { getters: true, virtuals: true } }
Detecting WhatIsIt
Starting to process "Group.rolesTest"
Final getType: dim: 0, type: class Role extends abstracts_1.AbstractModel {
    }
createArrayFromDimensions called with 1 dimensions
Applying Plugin: { mongoosePlugin: [Function: mongooseLeanDefaults],
  options: undefined }
Applying Plugin: { mongoosePlugin: [Function], options: undefined }
Applying Plugin: { mongoosePlugin: [Function: plugin], options: undefined }
```

**Comment by hasezoey** [comment] 2020-10-05 09:49
if you do "that workaround", how does it know that it is an array?

could you also provide the output of
```ts
import { schema } from "@typegoose/typegoose/lib/internal/data";
console.log("schema", schema.get(getName(YourClassHere)));
```

PS: does it work without the `hide` option, or is that the problem?

**Comment by benjaminb-** [comment] 2020-10-05 09:59
> if you do "that workaround", how does it know that it is an array?
> 
> could you also provide the output of (while using the not working code)
> 
> ```ts
> import { schema } from "@typegoose/typegoose/lib/internal/data";
> console.log("schema", schema.get(getName(YourClassHere)));
> ```
> 
> PS: does it work without the `hide` option, or is that the problem?

the console log is undefined, maybe i m not sure how to use it ?

Yes everything is working perfectly, just the `hide` option,
i tried the `hide` option with Mongoose and it s working well too 

but as you can see the options are set exactly like my workaround exemple, outside of the type

```
const TagSchema = new mongoose.Schema(
        {
          name: String
        },
        { _id: false }
      );
      const PostSchema = new mongoose.Schema(
        {
          title: String,
          tags: { type: [TagSchema], hide: true }
        },
        {
          timestamps: { createdAt: "created", updatedAt: "modified" }
        }
      );
```

**Comment by hasezoey** [comment] 2020-10-05 12:25
the schema you made in mongoose is not *an reference* it is *an subdocument (embedded)*

**Comment by hasezoey** [comment] 2020-10-05 12:44
i dont know at what level the `hide` option needs to be (could get any information from the plugin (documentation and tests)), so i cannot tell if this is an problem, anyway here it the code i use to log all information (and to get an common ground):

```ts
// NodeJS: 14.10.0
// MongoDB: 4.2-bionic (Docker)
import { getModelForClass, getName, prop, Ref } from "@typegoose/typegoose"; // @typegoose/typegoose@7.4.0
import { schemas } from "@typegoose/typegoose/lib/internal/data";
import * as mongoose from "mongoose"; // mongoose@5.10.6 @types/mongoose@5.7.36

class Role {
  @prop()
  public dummy?: string; // class was never provided
}

const RoleModel = getModelForClass(Role);

class User {
  @prop({ ref: "Role", hide: true })
  public roles?: Ref<Role>[];
}
const UserModel = getModelForClass(User);

(async () => {
  await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verify397", useCreateIndex: true, useUnifiedTopology: true });

  const role1 = await RoleModel.create({ dummy: "hi" });
  const user1 = await UserModel.create({ roles: [role1] });

  const foundUser1 = await UserModel.findById(user1);

  console.log("foundUser1", foundUser1);

  console.log("schema map", schemas.get(getName(User)));

  console.log("schema path", UserModel.schema.path("roles"));

  await mongoose.disconnect();
})();
```

<details>
<summary>Console Output</summary>

```ts
foundUser1 {
  roles: [ 5f7b1218a7fc5c20882ed76b ],
  _id: 5f7b1219a7fc5c20882ed76c,
  __v: 0
}
schema map { roles: [ { type: [Function], ref: 'Role', hide: true } ] }
schema path SchemaArray {
  schemaOptions: {
    typePojoToMixed: true,
    typeKey: 'type',
    id: true,
    noVirtualId: false,
    _id: true,
    noId: false,
    validateBeforeSave: true,
    read: null,
    shardKey: null,
    autoIndex: null,
    minimize: true,
    discriminatorKey: '__t',
    optimisticConcurrency: false,
    versionKey: '__v',
    capped: false,
    bufferCommands: true,
    strictQuery: false,
    strict: true,
    pluralization: true
  },
  casterConstructor: [Function: ObjectId] {
    schemaName: 'ObjectId',
    defaultOptions: {},
    get: [Function (anonymous)],
    set: [Function: set],
    _checkRequired: [Function (anonymous)],
    _cast: [Function: castObjectId],
    cast: [Function: cast],
    checkRequired: [Function (anonymous)]
  },
  caster: ObjectId {
    path: 'roles',
    instance: 'ObjectID',
    validators: [],
    getters: [],
    setters: [],
    options: SchemaObjectIdOptions { ref: 'Role', hide: true },
    _index: null,
    _arrayPath: 'roles.$',
    [Symbol(mongoose#schemaType)]: true
  },
  '$embeddedSchemaType': ObjectId {
    path: 'roles',
    instance: 'ObjectID',
    validators: [],
    getters: [],
    setters: [],
    options: SchemaObjectIdOptions { ref: 'Role', hide: true },
    _index: null,
    _arrayPath: 'roles.$',
    [Symbol(mongoose#schemaType)]: true
  },
  '$isMongooseArray': true,
  path: 'roles',
  instance: 'Array',
  validators: [],
  getters: [],
  setters: [],
  options: SchemaArrayOptions { type: [ [Object] ] },
  _index: null,
  defaultValue: [Function: defaultFn] { '$runBeforeSetters': true },
  [Symbol(mongoose#schemaType)]: true
}
```

</details>

PS: i didnt add the plugin, because from what i know the issue is about where the `hide` option is placed (and misunderstanding of references in typegoose) and because i dont know the plugin, or what it should achieve 
-> i think it would be good to create an issue at the plugin asking where the option needs to be placed in an reference-array
-> and maybe to add this option to `SchemaTypeOptions` (native mongoose)
-> (if you should create an issue, please add an link in this issue)

**Comment by benjaminb-** [comment] 2020-10-06 01:56
Thanks a lot for your feedback, I'm gonna create an issue in mongoose hidden

**Comment by hasezoey** [comment] 2021-10-02 10:51
closing this issue, because it is not a typegoose issue

as for the status, it seems like the plugin `mongoose-hidden` did not update yet to include the SchemaOption

**Closed by hasezoey** 2021-10-02 10:51 UTC
Labels: bug
