### ISSUE TITLE
Can't push nested field to a document

### ISSUE THREAD

**Issue by JimmyRowland** [typegoose/typegoose#323] opened 2020-07-14 00:43 UTC
I am trying to add a post to posts field. Instead of pushing post directly into posts field, [post] is pushed into the array and result
would look like posts == [[post]]

Here is my team document file
```ts
import { ObjectType, Field } from "type-graphql";
import { getModelForClass, prop, Ref } from "@typegoose/typegoose";

@ObjectType()
export class Team {
    @Field()
    @prop({ required: true })
    name: string;

    @Field(() => [Post])
    @prop({ default: [] })
    posts: Post[];
}
export const TeamModel = getModelForClass(Team);
```
Here is my post file:
```ts
import { ObjectType, Field, Root } from "type-graphql";
import { prop, Ref } from "@typegoose/typegoose";
@ObjectType()
export class Post extends CreationAndModificationDate {
    @Field()
    @prop({ required: false })
    content: string;
}
```

Here is my team resolver:
```ts
import { Resolver, Mutation, Query, Arg, Ctx, UseMiddleware, FieldResolver, Root } from "type-graphql";
import { ObjectID } from "mongodb";
@Mutation(() => Boolean)
    @UseMiddleware(isAuth, isMember)
    async addPost(@Arg("teamID") teamID: string, @Arg("content") content: string, @Ctx() { payload }: ResReq) {
        const team = await TeamModel.findById(teamID);
        if (!team) return false;
        const post = new Post();
        post.content = content;
        post.user = new ObjectID(payload._id);
        // const posts = team.posts.concat(post);
        const posts = team.posts;
        posts.push(post);
        const array: Post[] = [];
        array.push(post);
        posts.concat(post);
        try {
            team.posts = posts;
            team.save();
            await TeamModel.findByIdAndUpdate(teamID, { $push: { posts: post } });
            const updated = await TeamModel.findById(teamID);
            if(updated){
                console.log(post, posts, updated, array);
               // post is post object, posts: [Array<post>],  array.posts:  [Array<post>], array:[post]
            }
        } catch (e) {
            console.log(e);
            return false;
        }
        return true;
    }
}
```

log:
```
Post { content: 'someContent', user: 5f0ce186340d5d4e7e2acb2c } [[{"content":"someContent","user":"5f0ce186340d5d4e7e2acb2c"}]] {
  creationDate: 2020-07-13T23:31:34.538Z,
  lastModifyDate: 2020-07-13T23:31:34.538Z,
  posts: [ [ [Object] ] ],
  events: [],
  _id: 5f0cfe2c6b6dcf3d60d7496d,
  name: 'new2',
  __v: 1
} [ Post { content: 'someContent', user: 5f0ce186340d5d4e7e2acb2c } ]
```

As shown, the behavior of document.field.push is unexpected. How do I solve the problem?

Thanks

## Versions

- typegoose: 7.3.0
- mongoose: 5.7.14

**Comment by hasezoey** [comment] 2020-07-14 01:17
Duplicate of #300

**Closed by hasezoey** 2020-07-14 01:17 UTC
Labels: question
