### ISSUE TITLE
Returning arrays of each object inside array

### ISSUE THREAD

**Issue by plaskevich** [typegoose/typegoose#405] opened 2020-11-02 14:57 UTC
## Versions

- NodeJS: 12.18.3
- Typegoose(NPM): 7.4.1 
- mongoose: 5.10.11
- mongodb: 3.6.2

## What is the Problem?

When querying document, which contains array of objects, it returns every object in array inside the normal array.
So instead of `[{"role":"admin","userId":"5246321"},{"role":"regular","userId":"024211"}]`
I am receiving `[[{"role":"admin","userId":"5246321"}],[{"role":"regular","userId":"024211"}]]`

## Code Example

Here is my model
```ts
class Shop {
  @prop({ required: true })
  name!: string;
  @prop()
  users!: ShopUser[];
}

interface ShopUser {
  userId: String;
  role: Role
}

export enum Role {
  admin,
  regular
}
```

And the query
```ts
export async function getShop(_: any, { id }: { id : string }) {
  const shop = await ShopModel.findById(id);
  return shop
}
```

## Do you know *why* it happens?

No, however if in the model I remove the array and just leave `ShopUser` then it returns array as it should. But then it is not treated as an array so I can't do any array operations (push elements, etc.)

**Comment by hasezoey** [comment] 2020-11-02 15:23
Duplicate of #384

**Closed by hasezoey** 2020-11-02 15:23 UTC
Labels: bug
