### ISSUE TITLE
Move some things to metadata instead of data.ts

### ISSUE THREAD

**Issue by hasezoey** [typegoose/typegoose#44] opened 2019-09-22 17:12 UTC
- [x] Move Hooks cache to metadata instead of data.ts
- [x] Move VirtualPopulate cache to metadata instead of data.ts
- [x] Move Plugins to metdata
- [x] Move Decorators Cache to metadata

**Comment by captaincaius** [comment] 2019-09-25 08:58
:D oops ...

I think #46 might be a semi-duplicate of this.  I should have been more creative with my search keywords.

I just noticed you didn't mention schemas in this issue, and I'm guessing there's a good reason why.

Anyway please feel free to close that issue if you think it's too related to this.

**Comment by hasezoey** [comment] 2019-09-25 10:09
> I just noticed you didn't mention schemas in this issue, and I'm guessing there's a good reason why.

hooks & virtuals are for one class, which dosnt need to be modified

schemas could be moved to the class too

but other things like the model-cache & constructor-cache cannot be moved, because it is needed in functions where the class is unkown (`getClassForDocument.test`)

**Comment by hasezoey** [comment] 2019-10-17 01:10
thanks to #50, the decorator cache is now in the class itself

**Comment by hasezoey** [comment] 2020-04-14 13:01
all move-able data values are moved to reflection since e57b995a3f628564353cf9dd2e6a13e981b16869

**Closed** 2020-04-14 13:01 UTC
Labels: discussion, enhancement
