### ISSUE TITLE
Update/updateOne typings

### ISSUE THREAD

**Issue by Christilut** [typegoose/typegoose#170] opened 2019-12-27 10:35 UTC
## Describe what you need | want

Right now you lose typing information if you perform an update query, eg:
```
UserModel.updateOne('123', {
  'location.address.street': 'something'
})
```

Maybe with Typegoose we can add typings here?

For updateOne and update methods.

## Do you have already an idea for the implementation?

There is a mongoose helper on the document already:
```
const user = await UserModel.findOne('123')

user.updateOne({
  'location.address.street': 'something'
})
```
Maybe that method can be overwritten?

**Comment by hasezoey** [comment] 2019-12-27 10:43
https://typegoose.github.io/typegoose/guides/faq/#why-does-new-model-dont-have-types

Typegoose dosnt modify any functions of mongoose (or its types)

---

> There is a mongoose helper on the document already:

what do you mean with that?

**Comment by hasezoey** [comment] 2019-12-27 10:44
Duplicate of #150

**Closed by hasezoey** 2019-12-27 10:44 UTC
Labels: duplicate, feature, wont fix

**Comment by Christilut** [comment] 2019-12-27 10:59
I understand you don't want to modify the mongoose methods, but can't you make a wrapper around it?

Something like
```
UserModel.updateOne('123', {
  'location.address.street': 'something'
})
```

Can be a typegoose method with correct typing which in turn just calls the mongoose method with the same name?

Adding `as User` works but it's kind of a workaround that typegoose can do automatically?

**Comment by hasezoey** [comment] 2019-12-27 11:00
> Can be a typegoose method with correct typing which in turn just calls the mongoose method with the same name?

no i couldnt (at least not with the same name), because it would conflict with the original, and typegoose dosnt aim to re-type mongoose

**Comment by Christilut** [comment] 2019-12-27 11:01
Too bad :/

**Comment by beaulac** [comment] 2020-02-12 18:51
@Christilut [Augmenting](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation) mongoose's interfaces could achieve what you're looking for.
 
Here's an example of an augmentation to add a parameter that's missing in @types/mongoose definitions:

```ts
/**
 * Add replaceOne signatures until this issue is resolved:
 * https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34603
 */
declare module 'mongoose' {
  export interface Model<T extends Document, QueryHelpers = {}> {
    replaceOne(conditions: any,
               replacement: any,
               options: QueryFindOneAndUpdateOptions,
               callback?: (err: any, raw: any) => void): Query<any> & QueryHelpers;
  }
}
```

You could add a signature for `updateOne` that matches what you want.
