### ISSUE TITLE
Updating a document with nested discriminator does nothing, findOne is executed instead of findOneAndUpdate

### ISSUE THREAD

**Issue by GustavPS** [typegoose/typegoose#869] opened 2023-07-11 13:57 UTC
## Versions

- System: linux / windows 
- NodeJS: 18.15.0
- Typescript: 5.1.6

- Compiler / Transpiler: tsc
- Typegoose(NPM): 11.3.0 
- Typegoose(GIT): bc13b7a0e5be4cedfb6f0c078dfc02b3da5cc92f
- mongoose: 7.3.0 
- mongodb: 3.6.4 **and** 6.0.4

## What is the Problem?

When trying to update a field that exists in a nested list of discriminators, nothing is happening. Looking at the mongoose logs "findOne" is executed instead of "findOneAndUpdate"

## Code Example

The basic structure the schema needs to replicate this behaviour is this:

```json
{
  listWithoutDiscriminator: [
    {
      listWithDiscriminators: []
    }
  ]
}

```

**Models (Parent.ts)**
```ts
import { modelOptions, prop, getModelForClass } from "@typegoose/typegoose";

export enum Types {
  TypeWithPropA = 'typeWithPropA',
  TypeWithPropB = 'typeWithPropB'
};

@modelOptions({
  schemaOptions: {
    discriminatorKey: 'type',
    _id: false
  }
})
abstract class Base {
  @prop({ required: true })
  commonProp: string;

  @prop({ enum: Types, required: true, type: String })
  type: Types;
}

class PropA extends Base {
  @prop({ required: true })
  propA: string;
}

class PropB extends Base {
  @prop({ required: true })
  propB: string;
}

@modelOptions({
  schemaOptions: {
    _id: false
  }
})
class ContainNested {
  @prop({ required: true })
  containNestedCommonProp: string;

  @prop({
    required: true,
    type: Base,
    discriminators: () => [
      { type: PropA, value: Types.TypeWithPropA },
      { type: PropB, value: Types.TypeWithPropB }
    ]
  })
  listWithDiscriminators: Base[];
}


@modelOptions({
  schemaOptions: {
    collection: 'parent'
  }
})
export class Parent {
  @prop({ required: true })
  aRequiredProp: string

  @prop({ required: true, type: () => [ContainNested] })
  aList: ContainNested[];
}

export const ParentModel = getModelForClass(Parent);
```

**index.js**
```ts
import mongoose, { QueryOptions } from "mongoose";
import { ParentModel, Types } from "./Parent";


const connectToMongo = async () => {
  mongoose.set('debug', true);

  const uri = 'mongodb://localhost:27017';
  const dbName = 'verifyMASTER';
  await mongoose.connect(uri, {
    dbName
  });
  console.log('connected to mongodb');
};

const insertToDb = () => {
  // Inserting a document with an object of type "TypeWithPropA"
  // in the list with discriminators
  ParentModel.create({
    aRequiredProp: 'hello',
    aList: [
      {
        containNestedCommonProp: 'something-common',
        listWithDiscriminators: [
          {
            type: Types.TypeWithPropA,
            commonProp: 'this is the common prop',
            propA: 'this is propA'
          }
        ]
      }
    ]
  })
}

const updateSomething = async () => {
  const filter = {
    aRequiredProp: 'hello'
  };

  const updateQuery = {
    'aList.$[].listWithDiscriminators.$[id].propA': 'hello 123123'
  };

  const queryOptions: QueryOptions = {
    arrayFilters: [
      {
        'id.type': Types.TypeWithPropA
      }
    ]
  }

  await ParentModel.findOneAndUpdate(filter, updateQuery, queryOptions).exec();
};

const start = async () => {
  await connectToMongo();
  await insertToDb(); 

  /*
    This update does nothing if the type is set to the Base class in Parent.ts
  */
  await updateSomething()
};

start();
```

## Do you know *why* it happens?

*no*

---

This only happens if the discriminator is set on a list that is inside another list, if I change the structure to this (the discriminator inside the parent and not inside another list) the update works (with the modified update command).
```ts
@modelOptions({
  schemaOptions: {
    collection: 'parent'
  }
})
export class Parent {
  @prop({ required: true })
  aRequiredProp: string

  @prop({
    required: true,
    type: Base,
    discriminators: () => [
      { type: PropA, value: Types.TypeWithPropA },
      { type: PropB, value: Types.TypeWithPropB }
    ]
  })
  listWithDiscriminators: Base[];
}
```

It **also** works when changing the discriminator type from `Base` to `PropA || PropB`, or when setting `strict` to false for the update query.

Looking at the mongoose logs (from setting debug to true) i see this when I have the discriminator type set to `Base`:
`Mongoose: parent.findOne({ aRequiredProp: 'hello' }, { arrayFilters: [ { 'id.type': 'typeWithPropA' } ] })`
Notice that it's running **findOne**.

When I change it so the type is `PropA || PropB`, or set strict to `false`, or change so it's not a nested list I get the expect log from mongoose:
`Mongoose: parent.findOneAndUpdate({ aRequiredProp: 'hello' }, { '$set': { 'aList.$[].listWithDiscriminators.$[id].propA': 'hello 123123' }}, { arrayFilters: [ { 'id.type': 'typeWithPropA' } ] })`

**Comment by hasezoey** [comment] 2023-07-11 19:14
can reproduce in typegoose and pure mongoose

reproduction repository & branch: https://github.com/typegoose/typegoose-testing/tree/verify869

this does not seem to be a typegoose problem, maybe try opening a issue at mongoose (and reference this issue)

> or set strict to false

which `strict` are you setting to `false` and where?

**Comment by hasezoey** [comment] 2023-07-11 19:23
from my quick investigation, it seems like if the `update` path is a string and not a object, mongoose somehow uses `findOne` instead of `findOneAndUpdate`

example
```ts
// results in a "findOne" query
await ParentModel.findOneAndUpdate(
  {
    aRequiredProp: 'hello',
  },
  {
    'aList.0.listWithDiscriminators.0.propA': 'hello 123123',
  }
).exec();


// results in a "fineOneAndUpdate" query
await ParentModel.findOneAndUpdate(
  {
    aRequiredProp: 'hello',
  },
  {
    aList: {
      0: {
        listWithDiscriminators: {
          0: {
            propA: 'hello 123123',
          },
        },
      },
    },
  }
).exec();
```

**Comment by GustavPS** [comment] 2023-07-12 06:31
> can reproduce in typegoose and pure mongoose
> 
> reproduction repository & branch: https://github.com/typegoose/typegoose-testing/tree/verify869
> 
> this does not seem to be a typegoose problem, maybe try opening a issue at mongoose (and reference this issue)
> 
> > or set strict to false
> 
> which `strict` are you setting to `false` and where?

Thank you for your investigation! I will open a mongoose issue referencing this issue and using the branch you linked as reference for the mongoose code.

> which `strict` are you setting to `false` and where?

When I set strict to false in the `QueryOptions` like this I get `findOneAndUpdate` executed:
```ts
  const queryOptions: QueryOptions = {
    arrayFilters: [
      {
        'id.type': Types.TypeWithPropA
      }
    ],
    strict: false
  }
```

> from my quick investigation, it seems like if the `update` path is a string and not a object, mongoose somehow uses `findOne` instead of `findOneAndUpdate`

Very interesting, weird behavior. Will mentioon this in the issue

**Comment by hasezoey** [comment] 2023-11-12 15:58
closing because this is not a typegoose issue (from my quick skimming) and the mongoose issue has been closed https://github.com/Automattic/mongoose/issues/13604

**Closed by hasezoey** 2023-11-12 15:58 UTC
Labels: bug, not a typegoose issue
