### ISSUE TITLE
__uniqueID property being added to array, no idea why?

### ISSUE THREAD

**Issue by michaelbats** [typegoose/typegoose#105] opened 2019-11-01 14:15 UTC
Hi, I've noticed some of my arrays for some reason have this __uniqueID property added to it, no idea why:, here's the data:
```
    "projects": [
        {
            "_id": "B3oHPwxf4QzqDZBiw",
            "name": "North East Response 2018-19",
            "__uniqueID": 1572280187773
        },
        {
            "_id": "BTh5WJC8t55bRt75m",
            "name": "Thames Response 2018-20",
            "__uniqueID": 1572280187773
    ],
```

The model's property:

```
	@arrayProp({ items: Object, _id: false })
	@ValidateNested({ each: true })
	@Type(() => IdNameSchema)
	projects: IdNameSchema[];
```
The nested property:

```
export class IdNameSchema {
	@prop({ required: true })
	@Length(17, 17)
	@IsAlphanumeric()
	_id: string;

	@prop({ required: true })
	@IsString()
	@Length(1, 50)
	name: string;
}
```

The Extra decorators are from class-validator/class-transformer, used for validation separately.

I honestly have no idea where to look anymore as I can't find anything on google about that specific property name 

I've checked on the frontend and it is not being sent together with that

**Comment by RyannGalea** [comment] 2019-11-01 14:22
Does it happen without the validating decorators?

**Comment by michaelbats** [comment] 2019-11-01 14:23
Yes, forgot to mention! 

The DB is a Heroku addon on MLAB: mongod version: 3.6.9 (MMAPv1)

**Comment by hasezoey** [comment] 2019-11-01 14:50
`__uniqueID` was once used for identification purposes for DEO and shouldnt be available with an instance of a document, and now it is just there for typegoose "legacy" & "modding" purposes

-> does `__uniqueID` just come only with `console.log` or saved to the DB too? (because that shouldnt happen)

**Comment by michaelbats** [comment] 2019-11-01 16:22
```
    "typegoose": "^6.0.3",
    "mongoose": "^5.6.11",
    "nestjs-typegoose": "^7.0.0",
```

It is being retreived and sent back to the frontend and also added to the database; It is really weird to be honest as I haven't had this issue before and I've been using typegoose for quite a while :-?
 
I sadly can't do much about the database engine issue as it is part of a 'legacy' project; There is a separate api with meteor that writes to the DB without having that propery anywhere :-? so I don't think it's the engine itself.

To be honest I don't even know if it's typegoose but at this point I'm all out of ideas on where to even look;

Thanks for all the help!

**Comment by hasezoey** [comment] 2019-11-01 17:13
> To be honest I don't even know if it's typegoose but at this point I'm all out of ideas on where to even look;

like i said, it was made for the DEO(Decorator-Execution-Order) change, so: yes it is a typegoose variable - but it was never intended to be added to the database

-> that is why i asked for the version & if it happens without "class-transformer" & the other class thing

**Comment by hasezoey** [comment] 2019-11-01 17:21
otherwise, i cant reproduce your problem - i'm not using `nestjs-typegoose` / `class-transformer`

```ts
// NodeJS: 12.13.0
// MongoDB: 4.2-bionic (Docker)
import { arrayProp, getModelForClass, prop } from "@typegoose/typegoose"; // @typegoose/typegoose@6.0.4
import * as mongoose from "mongoose"; // mongoose@5.7.6

class IdNameSchema {
    // @prop({ required: true })
    // @Length(17, 17)
    // @IsAlphanumeric()
    // public _id!: string; // because "_id" is set to be turned of in parent class

    @prop({ required: true })
    // @IsString()
    // @Length(1, 50)
    public name!: string;
}

class Something {
    @arrayProp({ items: /* Object */IdNameSchema, _id: false }) // otherwise you would get "mongoose.Schema.Types.Mixed" which would allow any property, without validation / casting
    public projects!: IdNameSchema[];
}
const SomethingModel = getModelForClass(Something);

(async () => {
    await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verify105", useCreateIndex: true, useUnifiedTopology: true });

    const some = await SomethingModel.create({ projects: [{ name: "hello" }] } as Something);
    some.projects.push({ name: "another hello" });
    await some.save();

    console.log(some);

    await mongoose.disconnect();
})();
```

**Comment by hasezoey** [comment] 2019-11-03 11:00
@michaelbats is #108 your problem? when yes, please close this issue - thanks

**Comment by michaelbats** [comment] 2019-11-12 13:50
@hasezoey  sorry I've been focused on other parts of my app since then -- It is still occuring and not sure why. I am indeed using class-transformer and nestjs-typegoose. The DTO's themselves work for me and I am getting proper class validation. The validation pipes for nestjs has an option to transform the DTO's into their specified interface and maybe it works because of that? 

However with the use of nestjs and class-validators, the need for mongoose models themselves seems to shrink considerably. Perhaps it would be worth to explore the idea of typegoose to be based on class-validators to handle validation/DTO's and then just use mongodb's official package to interact with the database, bypassing the complexity of mongoose altogether.

**Comment by hasezoey** [comment] 2019-11-12 13:57
> Perhaps it would be worth to explore the idea of typegoose to be based on class-validators to handle validation/DTO's and then just use mongodb's official package to interact with the database, bypassing the complexity of mongoose altogether

the intention of typegoose (as the name has in it) to be a type-mongoose: typegoose, so it will ***Not*** be converted to bypassing mongoose

-> i actually made a test project, but never actually continued it - because i was busy for 6.0.0/6.1.0 and no mood to reinvent mongoose: https://github.com/hasezoey/typegoose-v2

**Comment by michaelbats** [comment] 2019-11-12 14:04
I wouldn't want to reinvent mongoose, I'd look at using mongodb to just :

     • handle connection pools
     • write data to a collection without validating/caring about the data at all
     • ensure/configure indexes

Everything else is completely unnecessary when already working with Typescript/Class Validators;

But that's just my biased 2c for the sake of discussion

**Comment by hasezoey** [comment] 2019-11-12 14:08
@michaelbats i will think about it

anyway, i will close this because i could not get to reproduce this
-> if you can upgrade to later typegoose (currently 6.1.2), please leave a comment / reopen if it still happens

**Closed by hasezoey** 2019-11-12 14:08 UTC
Labels: bug, cant reproduce, info needed

**Comment by hasezoey** [comment] 2019-11-12 14:35
@michaelbats, if you are interested, here https://github.com/hasezoey/typegoose-v2/issues/1 are the current problems i am/was facing when i made that project

**Comment by florianbepunkt** [comment] 2020-02-15 17:08
@hasezoey: I encouter the same issue with "@typegoose/typegoose": "6.3.2" and "mongoose": "^5.8.11". If I should open a new issue, please let me know.

I have the following two level nested structure like this (shortened for brevity). Each item of the `OrderItem.ancillaryServices` array has a prop called __uniqueID that is persisted to the database.

```
export default class Order extends BaseEntity {
  @prop({ required: true })
  public items!: OrderItem[];

  constructor(data: OnlyData<Order>) {
    super();

    Object.assign(this, data);
  }
}


export default class OrderItem {
  @arrayProp({ items: OrderItemAncillaryService })
  public ancillaryServices?: OrderItemAncillaryService[];

  constructor(data: OnlyData<OrderItem>) {
    Object.assign(this, data);
  }
}


export default class OrderItemAncillaryService {
  @prop()
  public grossPerUnit?: number;

  constructor(data: OnlyData<OrderItemAncillaryService>) {

    Object.assign(this, data);
  }
}

```

**Comment by hasezoey** [comment] 2020-02-23 17:29
@florianbepunkt i will remove it completly in 6.4.0

**Comment by florianbepunkt** [comment] 2020-02-25 11:42
@hasezoey Thank you. Is there a roadmap / plans on v2 of typegoose? I am using NestJs and it would be great to use class-transformer / validator with typegoose

**Comment by hasezoey** [comment] 2020-02-26 21:43
@florianbepunkt sorry to say this, but typegoose is already at v6, and going into v7 #113 (major updates, but not really modifying existing functionally)
