### ISSUE TITLE
How to create a Mixed array?

### ISSUE THREAD

**Issue by fromi** [typegoose/typegoose#410] opened 2020-11-10 13:33 UTC
I have a class with an array of Mixed values (on purpose, it is a framework requirement to handle any kind of data here).
I am migrating from 6.5.0 to 7.4.1.
I found many issues regarding Mixed arrays and the "type" property (such as https://github.com/typegoose/typegoose/issues/300)
I could not find the reason why objects inside the Mixed array gets wrapped into a array with one item, and how to prevent that? 

There is no documentation about how to create a Mixed array type properly.

Right now I have:
```
myArray: [
  [{data: 'myFirstObject'}]
  [{data: 'mySecondObject'}]
]
```

I expect:
```
myArray: [
  {data: 'myFirstObject'}
  {data: 'mySecondObject'}
]
```

Can I keep my mixed array without having all my objects wrapped in singleton arrays?

**Comment by hasezoey** [comment] 2020-11-10 13:40
please also provide the class with the property

**Comment by fromi** [comment] 2020-11-10 13:56
Sure, here it is:
```
@ObjectType({implements: GameNotification})
export default class MovePlayedNotification extends GameNotification {
  constructor(playerId: any, moveView: any, consequences: any[]) {
    super(getName(MovePlayedNotification), playerId)
    this.moveView = moveView
    this.consequences = consequences
  }

  @prop()
  moveView!: any

  @prop()
  consequences: any[] = []
}
```

**Comment by fromi** [comment] 2020-11-10 13:59
I just found a workaround:

```
@ObjectType({implements: GameNotification})
export default class MovePlayedNotification extends GameNotification {
  constructor(playerId: any, moveView: any, consequences: any[]) {
    super(getName(MovePlayedNotification), playerId)
    this.moveView = moveView
    this.consequences = consequences
  }

  @prop()
  moveView!: any

  @prop({type: Schema.Types.Mixed}) // <= here, explicit the Mixed type
  consequences: any[] = []
}
```
Any idea why setting explicitely the Mixed type changes the behavior and stops encapsulating every object into an array?

**Comment by hasezoey** [comment] 2020-11-10 14:01
Duplicate of #300

**Closed** 2020-11-10 14:01 UTC
Labels: question

**Comment by fromi** [comment] 2020-11-10 14:26
Well, that's not exactly a duplicate. The question is: why is the default type for an array prop `[Schema.Types.Mixed]` and not simply `Schema.Types.Mixed`?

**Comment by hasezoey** [comment] 2020-11-10 14:41
@fromi this is because the reflection type is `Array` (also used to detect that it is an array), and gets overridden by option `type`, and currently if it is not provided, it defaults to the reflection

should be defaulted in 7.4.2
