### ISSUE TITLE
Nested recursive properties crash

### ISSUE THREAD

**Issue by amirker** [typegoose/typegoose#106] opened 2019-11-02 08:27 UTC
## Versions

- NodeJS: 10.16.3
- Typegoose(NPM): 6.0.4 
- mongoose: 5.7.7
- mongodb: 4.0.0

## What is the Problem?

I upgraded library to see if v6.0 resolves this issue,
https://github.com/szokodiakos/typegoose/issues/321

but v6.0 is throwing an exception when using recursive nested properties:
Maximum call stack size exceeded (origin from buildSchema)

## Code Example

```ts
import * as mongoose from 'mongoose';
import { getModelForClass, arrayProp, prop } from '@typegoose/typegoose';

class NestedItem {
    @prop({ trim: true, required: true })
    public before?: string;

    @arrayProp({ items: NestedItem, _id: false })
    public items?: NestedItem[];

    @prop({ trim: true, required: true })
    public after?: string;
}

class Product {
    @prop()
    public name: string;

    @arrayProp({ items: NestedItem, _id: false })
    public items: NestedItem[];

    @prop()
    public rootAfter?: string;
}

const ProductModel = getModelForClass(Product);

(async () => {
    mongoose.set("debug", true);
    await mongoose.connect(`mongodb://mongod:27017/`, {
        useNewUrlParser: true,
        useFindAndModify: true,
        useCreateIndex: true,
        dbName: "verify321",
    });

    const item = new ProductModel({
        name: "My Product",
        items: [
            {
                before: "Item 1", after: "this will be saved, right?", items: [
                    { before: "Item 1-1", after: "this will not be saved, right?" },
                    { before: "Item 1-2", after: "this will not be saved, right?" }
                ]
            }
        ],
        rootAfter: "this is saved, right?"
    } as Product);

    const added = await item.save();

    const root = added.items[0];
    console.log(`Root before='${root.before}', after='${root.after}'`);
    console.log(`  Item1-1 before='${root.items[0].before}', after='${root.items[0].after}'`);
    console.log(`  Item1-2 before='${root.items[1].before}', after='${root.items[1].after}'`);

    await mongoose.disconnect();
})();
```

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment] 2019-11-02 08:57
Duplicate of #42

**Closed** 2019-11-03 10:52 UTC
Labels: bug, duplicate
