### ISSUE TITLE
Map in EmbededDocument, the set function error!

### ISSUE THREAD

**Issue by winnochan** [typegoose/typegoose#541] opened 2021-05-26 07:19 UTC
## Versions

- System: linux
- NodeJS: v12.16.3
- Typescript: 4.2.4

- Compiler / Transpiler: both tsc and ts-node
- Typegoose(NPM): 7.6.0
- mongoose: 5.10.18
- mongodb: 4.4.6

## What is the Problem?

When define a nested Map field in a NestedDocument, call the set function of nested Map field, the modified path is not automatically added, So the data will loss.

## Code Example

```ts
import {
  defaultClasses,
  getModelForClass,
  modelOptions,
  mongoose,
  prop,
} from "@typegoose/typegoose";
import { Types } from "mongoose";
import { nanoid } from "nanoid";

export class SecondMap {
  @prop({ _id: false, default: {}, type: Number })
  data?: Types.Map<number>;
}

export class FirstMap {
  @prop({ _id: false, default: {}, type: SecondMap })
  data?: Types.Map<SecondMap>;
}

export class Nested {
  @prop({ _id: false, default: {}, type: SecondMap })
  data?: Types.Map<SecondMap>;
}

@modelOptions({ schemaOptions: { versionKey: false } })
export class Test extends defaultClasses.Base<string> {
  @prop()
  _id: string;

  @prop({ _id: false, default: {}, type: FirstMap })
  firstMap?: Types.Map<FirstMap>;

  @prop({ _id: false, default: {} })
  nested?: Nested;
}

const TestModel = getModelForClass(Test);

function strify(obj: object, space?: string | number) {
  return JSON.stringify(
    obj,
    (_, v) => {
      if (v instanceof Set) return [...v];
      if (v instanceof Map) return Object.fromEntries(v);
      return v;
    },
    space
  );
}

async function testCase() {
  await mongoose.connect("mongodb://localhost:27017", {
    useCreateIndex: true,
    useNewUrlParser: true,
    useUnifiedTopology: true,
    useFindAndModify: false,
  });
  const doc = await TestModel.create({ _id: nanoid() });

  console.log(strify(doc, 4));

  console.log("Should empty", doc.modifiedPaths());

  // It's Ok!
  doc.firstMap.set("fisrt", {});
  console.log("Should include firstMap.first", doc.modifiedPaths());
  await doc.save();

  // It's Ok!
  doc.firstMap.get("fisrt").data.set("second", {});
  console.log("Should include firstMap.first.data.second", doc.modifiedPaths());
  await doc.save();

  // It's Ok!
  doc.firstMap.get("fisrt").data.get("second").data.set("final", 3);
  console.log(
    "Should include firstMap.first.data.second.data.final",
    doc.modifiedPaths()
  );
  await doc.save();

  // It's Ok!
  doc.nested.data.set("second", {});
  console.log("Should include nested.data.second", doc.modifiedPaths());
  await doc.save();

  // It's ERROR!
  doc.nested.data.get("second").data.set("final", 3);
  console.log(
    "Should include nested.data.second.data.final, but it's not, ERROR here!!! So data lossed!",
    doc.modifiedPaths()
  );
  await doc.save();

  console.log(strify(doc, 4));

  // But this is OK, have to set the nested to {}, I don't know why
  const okDoc = await TestModel.create({ _id: nanoid(), nested: {} });
  okDoc.nested.data.set("second", {});
  await okDoc.save();

  okDoc.nested.data.get("second").data.set("final", 3);
  console.log(
    "Should include nested.data.second.data.final",
    okDoc.modifiedPaths()
  );
  await okDoc.save();

  await mongoose.disconnect();
}

testCase();
```

## Do you know *why* it happens?

*no*

---

package.json:

```json
{
  "name": "typegoose-issues",
  "version": "1.0.0",
  "description": "",
  "main": "dist/index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@typegoose/typegoose": "^7.6.0",
    "@types/mongoose": "^5.10.5",
    "mongoose": "^5.10.18",
    "nanoid": "^3.1.23",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2"
  },
  "devDependencies": {
    "@types/node": "^15.6.1",
    "typescript": "^4.2.4"
  }
}

```

tsconfig.json:
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2019",
    "sourceMap": false,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true
  }
}
```

**Comment by hasezoey** [comment] 2021-05-26 09:29
do you mean with `But this is OK, have to set the nested to {}, I don't know why` that you have to add an `nested` property in the create, even though its optional?

**Comment by winnochan** [comment] 2021-05-26 10:17
@hasezoey Yes! I use only the mongoose(both 5.10.18 and 5.12.x) package to test this feature just now, and this is also failed! I think it is a bug of mongoose. I will create an issue to the mongoose repo later.

**Comment by hasezoey** [comment] 2021-05-26 14:42
confirmed bug, and confirmed it is not typegoose related, code used (slightly edited from original, cutting out parts that are not related):

```ts
// NodeJS: 16.1.0
// MongoDB: 4.2-bionic (Docker)
import { getModelForClass, prop } from "@typegoose/typegoose"; // @typegoose/typegoose@8.0.0-beta.9
import * as mongoose from "mongoose"; // mongoose@5.12.10
import { inspect } from "util";

class SecondMap {
  @prop({ _id: false, default: {}, type: Number })
  public data1?: mongoose.Types.Map<number>;
}

class FirstMap {
  @prop({ _id: false, default: {}, type: () => SecondMap })
  public data2?: mongoose.Types.Map<SecondMap>;
}

class Nested {
  @prop({ _id: false, default: {}, type: () => SecondMap })
  public data3?: mongoose.Types.Map<SecondMap>;
}

class Test {
  @prop({ _id: false, default: {}, type: FirstMap })
  public firstMap?: mongoose.Types.Map<FirstMap>;

  @prop({ _id: false, default: {} })
  public nested?: Nested;
}

const TestModel = getModelForClass(Test);

// const SecondMapSchema = new mongoose.Schema({
//   data1: {
//     _id: false,
//     default: {},
//     type: Map,
//     of: Number
//   }
// });
// const FirstMapSchema = new mongoose.Schema({
//   data2: {
//     _id: false,
//     default: {},
//     type: Map,
//     of: SecondMapSchema
//   }
// });
// const NestedSchema = new mongoose.Schema({
//   data3: {
//     _id: false,
//     default: {},
//     type: Map,
//     of: SecondMapSchema
//   }
// });
// const TestSchema = new mongoose.Schema({
//   firstMap: {
//     _id: false,
//     default: {},
//     type: Map,
//     of: FirstMapSchema
//   },
//   nested: {
//     _id: false,
//     default: {},
//     type: NestedSchema
//   }
// });

// const TestModel: any = mongoose.model("Test", TestSchema);

(async () => {
  await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verifyMASTER", useCreateIndex: true, useUnifiedTopology: true });

  const doc = await TestModel.create({});

  console.log(inspect(doc, false, 5));
  console.log("Should be empty", doc.modifiedPaths());

  // Ok!
  doc.firstMap.set("first", {});
  console.log("Should include firstMap.first", doc.modifiedPaths());
  await doc.save();

  // Ok!
  doc.firstMap.get("first").data2.set("second", {});
  console.log("Should include firstMap.first.data2.second", doc.modifiedPaths());
  await doc.save();

  // Ok!
  doc.firstMap.get("first").data2.get("second").data1.set("final", 3);
  console.log(
    "Should include firstMap.first.data2.second.data1.final",
    doc.modifiedPaths()
  );
  await doc.save();

  // Ok!
  doc.nested.data3.set("second", {});
  console.log("Should include nested.data3.second", doc.modifiedPaths());
  await doc.save();

  // ERROR!
  console.log("test1", doc.nested.data3);
  doc.nested.data3.get("second").data1.set("final", 3);
  console.log("test2", doc.nested.data3);
  console.log(
    "Should include nested.data3.second.data1.final",
    doc.modifiedPaths()
  );
  await doc.save();

  console.log(inspect(doc, false, 5));

  // This is OK, but have to set "nested" to "{}"
  const okDoc = await TestModel.create({ nested: {} });
  okDoc.nested.data3.set("second", {});
  await okDoc.save();

  okDoc.nested.data3.get("second").data1.set("final", 3);
  console.log(
    "Should include nested.data3.second.data1.final",
    okDoc.modifiedPaths()
  );
  await okDoc.save();

  await mongoose.disconnect();
})();
```

**Comment by hasezoey** [comment] 2021-06-04 18:11
it seems like this issue is gonna be fixed with mongoose 5.12.13

**Comment by winnochan** [comment] 2021-06-07 06:06
@hasezoey 5.12.13 has released, it will be supported in 8.x, right?

**Comment by winnochan** [comment] 2021-06-07 06:08
@hasezoey  I think it should be added to document to avoid this situation, which will loss data.

**Comment by hasezoey** [comment] 2021-06-07 09:13
when #549 gets merged, the minimal required mongoose version will be updated, so i think this is not required yet (but PR's are welcome)

**Comment by hasezoey** [comment] 2021-06-10 09:08
closing because 5.12.13 with the fix is released and is supported by typegoose

**Closed by hasezoey** 2021-06-10 09:08 UTC
Labels: bug, not a typegoose issue
