### ISSUE TITLE
Usage in the browser

### ISSUE THREAD

**Issue by dandv** [typegoose/typegoose#250] opened 2020-05-08 19:10 UTC
I'm trying to use the [`isDocument`](https://typegoose.github.io/typegoose/docs/functions/typeguards/isDocument/) type guard in React code that fetches a `Post` object via GraphQL. I need only the `Post` class, and no model capabilities, since I'm not using `mongoose` on the frontend only on the backend, powering the GraphQL server). Is there a proper way to do this?

I installed @typegoose/typegoose and mongoose in my Gatsby/React project and tried,

```js
import { isDocument } from `@typegoose/typegoose`;
...
if (!isDocument(post.author)) throw ...
```

but I get this error:

![image](https://user-images.githubusercontent.com/33569/81440361-09aa6180-91c4-11ea-855e-24032a60045d.png)

## Versions

- typegoose: 7.0.0
- mongoose: 5.9.12

**Comment by hasezoey** [comment] 2020-05-08 19:37
even if typegoose was made compatible with the browser, you couldnt use typeguards, because they depend on the data using mongoose model/documents, and in the checks it uses mongoose too - so they will never work in an browser

otherwise this might be an duplicate of #33 
-> and as i said in there, im willing to look into prs for this if any get made

**Comment by hasezoey** [comment] 2020-07-15 16:50
Duplicate of #33

**Closed by hasezoey** 2020-07-15 16:50 UTC
Labels: question
