### ISSUE TITLE
Generic type 'Query<ResultType, DocType, THelpers>' requires between 2 and 3 type arguments.

### ISSUE THREAD

**Issue by hnviradiya** [typegoose/typegoose#521] opened 2021-04-10 04:23 UTC
## Versions

- System: windows
- NodeJS: v14.15.5
- Typescript: 4.2.4
- Compiler / Transpiler: tsc / ts-node 
- Typegoose(NPM): 7.6.0
- Typegoose(GIT): commithash
- mongoose: 5.12.3
- mongodb: 3.6.6

## What is the Problem?

Type definition gives below error.
Generic type 'Query<ResultType, DocType, THelpers>' requires between 2 and 3 type arguments.
![image](https://user-images.githubusercontent.com/12680915/114258043-88fe7180-99e1-11eb-9920-92fc95de16d3.png)

## Code Example

Not related to my code. It seems internal typegoose type error.

## Do you know *why* it happens?

May be related to https://github.com/Automattic/mongoose/issues/9606#issuecomment-736527902
If I downgrade mongoose to "mongoose": "^5.10.19", then it works.

---

**Comment by smolinari** [comment] 2021-04-10 06:09
@hnviradiya - Typegoose 7 only works with up to Mongoose 5.10.18. Either downgrade to Mongoose 5.10.18 and install @types/mongoose (if not already done) or upgrade to Typegoose 8 (which is in beta)(and remove @types/mongoose). 

Scott

**Comment by hasezoey** [comment] 2021-04-10 06:18
Duplicate of #432

**Closed by hasezoey** 2021-04-10 06:18 UTC
Labels: bug
