### ISSUE TITLE
Instance methods are not filtered out, like in AnyBulkWriteOperation<Schema>

### ISSUE THREAD

**Issue by a-ledu** [typegoose/typegoose#825] opened 2023-04-18 16:14 UTC
Hi and thanks for this nice package :)

## Versions
System: macos / windows
Typegoose: 11.0.0,
NodeJS: 19.8.1
Typescript: 5.0.4
mongoose: 7.0.3

## What is the Problem?

I try to use AnyBulkWriteOperation<KittenClass> to type bulkWrite operation but only works when the class do not have instance methods.
If the class have instance method, I get :

```
TS2322: Type '{ species: string; }' is not assignable to type 'OptionalId<KittenClass>'. 
Property 'setSpeciesAndSave' is missing in type '{ species: string; }' but required in type 'Pick<KittenClass, keyof KittenClass>'.

bug-typegoose.ts(13, 16): 'setSpeciesAndSave' is declared here.
mongodb.d.ts(3642, 5): The expected type comes from property 'document' which is declared here on type 'InsertOneModel<KittenClass>'
```

I am not sure if it's typegoose or mongoose related.

## Code Example

```ts
import * as mongoose from 'mongoose';
import { getModelForClass, prop, DocumentType } from '@typegoose/typegoose';
import { AnyBulkWriteOperation } from 'mongodb';

class KittenClass {
  @prop()
  public name?: string;

  @prop()
  public species?: string;

  // the "this" definition is required to have the correct types
  public async setSpeciesAndSave(this: DocumentType<KittenClass>, species: string) {
    this.species = species;
    await this.save();
  }
}

const KittenModel = getModelForClass(KittenClass);

(async () => {
  await mongoose.connect('mongodb://localhost:27017/', {
    dbName: 'test',
  });

  const doc = new KittenModel({ username: 'user1' });
  await doc.setSpeciesAndSave('cat');
  const updateOneKitten: AnyBulkWriteOperation<KittenClass> = {
    insertOne: {
      document: {
        species: 'dog',
      },
    },
  };
  await KittenModel.bulkWrite([updateOneKitten]);
  console.log(doc);

  await mongoose.disconnect();
})();

```

## Do you know *why* it happens?

No

**Comment by hasezoey** [comment] 2023-04-19 07:53
kind of a known issue, the problem is that classes are mixed properties and functions and mongoose expects them to be separated, but filtering the classes into those 2 things is somewhat unstable (to my understanding) in typescript and (from what i can tell) somewhat performance intensive. so for now you will have to use a workaround:

```ts
  const updateOneKitten: AnyBulkWriteOperation<Partial<KittenClass>> = {
    insertOne: {
      document: {
        species: 'dog',
      },
    },
  };
  await KittenModel.bulkWrite([updateOneKitten as any]);
```
this will not remove the function from the type, but it will make it optional, downside is it makes everything optional

i will keep this issue open, because it is a known issue. i will try to add some kind of filter type later

**Comment by hasezoey** [comment] 2023-04-19 09:03
added a helper type, i dont know about its performance but it will be available starting typegoose 11.0.2 under the name [`FilterOutFunctionKeys`](https://typegoose.github.io/typegoose/docs/api/types/utility-types#filteroutfunctionkeyst)

**Comment by hasezoey** [comment] 2023-04-19 09:19
also made a mongoose PR to allow overwriting `bulkWrite` types to not require the `as any` like in the workaround https://github.com/Automattic/mongoose/pull/13292

**Comment by a-ledu** [comment] 2023-04-19 09:40
Thanks for quick support !
I was aware of the workaround but it would be much better with the new way indeed without optional and any (if there is no performance issue of course)

**Comment by hasezoey** [comment] 2023-06-09 19:32
the helper type is in typegoose and the mongoose issue is also closed and released

closing as a "wont fix further" (no automatic filtering by default)

**Closed by hasezoey** 2023-06-09 19:32 UTC
Labels: enhancement
