### ISSUE TITLE
Cast to Embedded failed

### ISSUE THREAD

**Issue by fcpauldiaz** [typegoose/typegoose#626] opened 2021-10-18 21:50 UTC
It looks like mongoose is receiving a string instead of the actual array. 

Error
```bash
 errors: {
    name: CastError: Cast to Embedded failed for value "[ { value: 'test', language: 'en-us' } ]" (type Array) at path "name"
        at model.$set (/Users/fcpauldiaz/Documents/beon/px/app/node_modules/mongoose/lib/document.js:1454:9)
        at model.$set (/Users/fcpauldiaz/Documents/beon/px/app/node_modules/mongoose/lib/document.js:1149:16)
        at model.Document (/Users/fcpauldiaz/Documents/beon/px/app/node_modules/mongoose/lib/document.js:158:12)
        at model.Model (/Users/fcpauldiaz/Documents/beon/px/app/node_modules/mongoose/lib/model.js:106:12)
        at new model (/Users/fcpauldiaz/Documents/beon/px/app/node_modules/mongoose/lib/model.js:4755:15)
        at /Users/fcpauldiaz/Documents/beon/px/app/node_modules/mongoose/lib/model.js:3113:22
        at /Users/fcpauldiaz/Documents/beon/px/app/node_modules/mongoose/lib/model.js:3149:7
        at Array.forEach (<anonymous>)
        at /Users/fcpauldiaz/Documents/beon/px/app/node_modules/mongoose/lib/model.js:3148:15
        at /Users/fcpauldiaz/Documents/beon/px/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5 {
      stringValue: `"[ { value: 'test', language: 'en-us' } ]"`,
      messageFormat: undefined,
      kind: 'Embedded',
      value: [Array],
      path: 'name',
      reason: [ObjectExpectedError],
      valueType: 'Array'
    }
  },
  _message: 'Survey validation failed'
```

Model 
````ts
import { getModelForClass, prop } from "@typegoose/typegoose";
import { models } from "mongoose";

class SurveyQuestionCategory {
  @prop({ type: () => Number })
  public category_id?: number;

  @prop({ type: () => String })
  public name?: string;
}
class SurveyQuestionChoice {
  @prop({ type: () => String })
  public value?: string;

  @prop({ type: () => Number })
  public scale_value?: number;

  @prop({ type: () => Boolean })
  public is_correct?: boolean;
}
class SurveyQuestion {
  @prop({ type: () => Number })
  public order?: number;

  @prop({ type: () => String })
  public language?: string;

  @prop({ type: () => String })
  public name?: string;

  @prop({ type: () => String })
  public type?: string;

  @prop({ type: () => [SurveyQuestionChoice] })
  public choices?: SurveyQuestionChoice[];

  @prop({ type: () => [SurveyQuestionCategory] })
  public categories?: SurveyQuestionCategory[];
}

class SurveyName {
  @prop({ type: () => String })
  public value?: string;

  @prop({ type: () => String })
  public language?: string;
}

export class Survey {
  @prop({ default: false, type: () => Boolean })
  public is_published!: boolean;

  @prop({ type: () => [SurveyName] })
  public name?: SurveyName[];

  // @prop({ type: () => [SurveyQuestion] })
  // public questions?: SurveyQuestion[];
}

export default getModelForClass(Survey);
````
Object to save
```js
{
  owner_id: 1,
  name: [ { value: 'test', language: 'en-us' } ],
  questions: [
    {
      order: 0,
      categories: [],
      type: 'Likert Scale',
      language: 'en-us',
      name: 'test',
      choices: [Array]
    }
  ]
}
```

tsconfig.json

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "lib": [
      "dom",
      "dom.iterable"
    ],
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "strict": true,
    "downlevelIteration": true,
    "esModuleInterop": true,
    "module": "ESNext",
    "moduleResolution": "node",
    "isolatedModules": true,
    "jsx": "preserve",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "baseUrl": ".",
    "paths": {
      "@/lib/*": [
        "lib/*"
      ],
      "@/components/*": [
        "components/*"
      ],
      "@/layouts/*": [
        "layouts/*"
      ],
      "@/graphql/*": [
        "graphql/*"
      ],
      "@/models/*": [
        "models/*"
      ]
    },
    "allowJs": true,
    "types": [],
    "resolveJsonModule": true
  },
  "include": [
    "app.d.ts",
    "next-env.d.ts",
    "graphql",
    "lib",
    "components",
    "layouts",
    "pages",
    "utils"
  ],
  "exclude": [
    "**/node_modules",
    "**/.*/"
  ]
}
```

## Versions
Mongoose 6.0.11
Typegoose: 9.2.0
Typescript: 4.3.4
Node: 16.9.0

##Debug Level
```bash
Added "SurveyQuestionCategory.category_id" to the Decorator Cache
Added "SurveyQuestionCategory.name" to the Decorator Cache
Added "SurveyQuestionChoice.value" to the Decorator Cache
Added "SurveyQuestionChoice.scale_value" to the Decorator Cache
Added "SurveyQuestionChoice.is_correct" to the Decorator Cache
Added "SurveyQuestion.order" to the Decorator Cache
Added "SurveyQuestion.language" to the Decorator Cache
Added "SurveyQuestion.name" to the Decorator Cache
Added "SurveyQuestion.type" to the Decorator Cache
Added "SurveyQuestion.choices" to the Decorator Cache
Added "SurveyQuestion.categories" to the Decorator Cache
Added "SurveyName.value" to the Decorator Cache
Added "SurveyName.language" to the Decorator Cache
Added "Survey.is_published" to the Decorator Cache
Added "Survey.name" to the Decorator Cache
buildSchema called for "Survey"
Assigning global Schema Options to "Survey"
_buildSchema Called for Survey with options: {}
Detecting WhatIsIt
Starting to process "Survey.is_published"
Prop Option "type" is set to  [Function: type]
Final getType: dim: 0, type: [Function: Boolean]
Detecting WhatIsIt
Starting to process "Survey.name"
Prop Option "type" is set to  [Function: type]
Final getType: dim: 1, type: [class SurveyName]
buildSchema called for "SurveyName"
Assigning global Schema Options to "SurveyName"
_buildSchema Called for SurveyName with options: {}
Detecting WhatIsIt
Starting to process "SurveyName.value"
Prop Option "type" is set to  [Function: type]
Final getType: dim: 0, type: [Function: String]
Detecting WhatIsIt
Starting to process "SurveyName.language"
Prop Option "type" is set to  [Function: type]
Final getType: dim: 0, type: [Function: String]
buildSchema called for "SurveyName"
_buildSchema Called for SurveyName with options: {}
Detecting WhatIsIt
Starting to process "SurveyName.value"
Prop Option "type" is set to  [Function: type]
Final getType: dim: 0, type: [Function: String]
Detecting WhatIsIt
Starting to process "SurveyName.language"
Prop Option "type" is set to  [Function: type]
Final getType: dim: 0, type: [Function: String]
Class "Survey" already existed in the constructors Map
```

---

**Comment by fcpauldiaz** [comment] 2021-10-18 22:08
@hasezoey yes, that is the property that is having the error. I added the tsconfig and the debug.

**Comment by hasezoey** [comment] 2021-10-19 00:00
> I'm using next js which uses babel.
> The second suggestion fixed the error:

then you ran into [use without `emitDecoratorMetadata`](https://typegoose.github.io/typegoose/docs/guides/use-without-emitDecoratorMetadata)

see [Known Issues: Babel](https://typegoose.github.io/typegoose/docs/guides/known-issues#babel)

---

i will close this issue, because the problem is known, and typegoose can do nothing about it

PS: you can also use `@prop({ type: () => [SurveyName] }, WhatIsIt.ARRAY)`, i just wanted to make sure that the `() => []` notation was absolutely not the problem (because i didnt know about the use of `babel`) see [`@prop` option `dim`](https://typegoose.github.io/typegoose/docs/api/decorators/prop#dim)

**Closed by hasezoey** 2021-10-19 00:00 UTC
Labels: question
