### ISSUE TITLE
Getters and setters on props

### ISSUE THREAD

**Issue by josepmorey** [typegoose/typegoose#38] opened 2019-09-16 10:18 UTC
Hi!

Why prop decorator don't accept get and set option? Thanks

[https://mongoosejs.com/docs/tutorials/getters-setters.html](url)

**Comment by hasezoey** [comment] 2019-09-16 11:20
When you ask such question(s), please always provide which versions you are using (mongoose & typegoose)

**Comment by hasezoey** [comment] 2019-09-16 13:32
pushed it, when travis has build & github has updated, it can [be found here](https://hasezoey.github.io/typegoose/docs/decorators/prop/#get--set)

**Comment by hasezoey** [comment] 2019-09-24 15:59
Closing this because `get` & `set` are confirmed working, but only in version 6

**Closed by hasezoey** 2019-09-24 15:59 UTC
Labels: question
