### ISSUE TITLE
[Question] Type is invalid error

### ISSUE THREAD

**Issue by remi2j** [typegoose/typegoose#43] opened 2019-09-22 14:20 UTC
Hi @hasezoey , thanks for maintaining this project

I just refactored a project to use Typegoose instead of just Mongoose. I'm using the 6.0 "next" version on NPM. But when I start my server, I get this error:

`Error: "undefined.users"'s Type is invalid! Type is: "undefined"`

The error is quite vague, and it's hard to know where it comes from, especially since I just made a lot of changes. All I know is that `users` is one of my collections.

Is it introspecting my database to see if it matches the generated schema ? Did I mess up a `prop()` ?

Thanks

**Comment by hasezoey** [comment] 2019-09-22 14:50
> The error is quite vague,

i actually tried to make the errors as "not vague" as possible, it is in the format of "Class.Property"

so it means:
1. your class is given as undefined (or the name is just got wrong, happens sometimes)
2. the Type of "users" is not a correct type (typegoose found the type as "undefined")

for more help i would need the model it errors on, and sorry for the wrong stacktrace, this is because of DEO (#23,#24)

**Comment by remi2j** [comment] 2019-09-22 16:20
Thanks for the quick response.

I thought it was a problem with my User model, but since the `users` in the error message is a property, I found that it comes from another model (Brand) that has a `users` property. It's a reference to the User model.

Here's how it's defined:

```typescript
class Brand {
  // Other props above

  @arrayProp({ itemsRef: User })
  users: Ref<User>[]
}
const BrandModel = getModelForClass(Brand)
```
where User is a class with @prop attributes from another file.

Removing the `users` attribute from the Brand gets rid of the error, but how can I actually fix this ?

**Comment by hasezoey** [comment] 2019-09-22 16:57
could you do a minimal repo script?

**Comment by remi2j** [comment] 2019-09-22 21:27
You nailed it:

- I updated to version 30 and it confirmed the error came from the Brand model
- Setting the ref as a string fixed the error

Thanks for the help!

Unrelated: I noticed the repo changed ownership, so you should change the link to the Github pages site in the repo's description

**Comment by hasezoey** [comment] 2019-09-22 22:33
> Unrelated: I noticed the repo changed ownership, so you should change the link to the Github pages site in the repo's description

i will, once i release version 6.0.0, for now github just redirects to here :)

so, this issue is solved now? when yes you can close this

**Closed** 2019-09-22 23:08 UTC
Labels: question

**Comment by ChrisLahaye** [comment] 2020-04-24 12:09
This issue is back at 7.0.0

**Comment by hasezoey** [comment] 2020-04-24 12:16
@ChrisLahaye please open a new issue with reproduction code
