### ISSUE TITLE
_id is undefined on virtual property

### ISSUE THREAD

**Issue by KROSF** [typegoose/typegoose#96] opened 2019-10-23 19:52 UTC
## Versions

- NodeJS: 12.13.0
- Typegoose(NPM): 6.0.4
- mongoose: 5.7.6
- mongodb: 4.2.0 (docker 4.2.0-bionic)
  
## What is the Problem?

I want my model to have a virtual property relayId but `this._id` always return undefined

## Code Example

```ts
import { prop as Property } from '@typegoose/typegoose'
import { Base } from '@typegoose/typegoose/lib/defaultClasses'

@ObjectType({ implements: Node })
export class User extends Base implements Node {
  @Field(() => ID, { name: 'id' })
  public get relayId (): string {
    console.log(this._id) // undefined
    console.log(this._doc._id) // this works
    return toGlobalId('User', this._id) // undefined
  }
}
```

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment] 2019-10-23 22:54
Cannot reproduce, code used:

```ts
// NodeJS: 12.13.0
// MongoDB: 4.2-bionic (Docker)
import { DocumentType, getModelForClass, prop } from "@typegoose/typegoose"; // @typegoose/typegoose@6.0.4
import { Base } from "@typegoose/typegoose/lib/defaultClasses";
import * as mongoose from "mongoose"; // mongoose@5.7.6

class User extends Base /* implements Node */ {
    public get relayId(this: DocumentType<User>): string {
        console.log(this._id); // undefined
        console.log((this as any)._doc._id); // this works
        return this._id; // undefined
    }
}
const UserModel = getModelForClass(User);

(async () => {
    await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verify96", useCreateIndex: true, useUnifiedTopology: true });

    const createdUser = await UserModel.create({});
    console.log(createdUser);
    console.log(createdUser.relayId);

    await mongoose.disconnect();
})();
```

**Comment by RyannGalea** [comment] 2019-10-23 22:59
If you are using 'type-graphql' as I think you are, you can use the @Root method to get the parent which is a clean way of doing it, an example below:

```
import { Field, ObjectType, Root } from 'type-graphql'

@ObjectType({ implements: Node })
export class User extends Base implements Node {
  @Field(() => ID, { name: 'id' })
  public get relayId (@Root() parent: User): string {
    const { _id } = parent
    return toGlobalId('User', _id)
  }
}

```

**Comment by KROSF** [comment] 2019-10-27 16:18
@hasezoey I'm sorry for taking so long to respond.
I created a [repository](https://github.com/KROSF/typegoose-base-id) that reproduces the error.
I hope it helps.

**Comment by KROSF** [comment] 2019-10-27 16:26
@RyannGalea I tried your proposal but the first one is imposible a getter cannot has a parameters.
The second looked promising but didn't work 😭

**Comment by hasezoey** [comment] 2019-10-28 04:19
@KROSF, i cloned your repo - i dont see anything obvious, i ran it - it compiled fine, but i dont know how to use your code (never worked with nestjs/type-graphql)

**Comment by RyannGalea** [comment] 2019-10-28 07:48
@KROSF you would have to remove get as i forgot too.

**Comment by KROSF** [comment] 2019-11-01 17:45
@hasezoey sorry for my bad explanation, I update the [Readme](https://github.com/KROSF/typegoose-base-id) with minimal guide.
I also migrated from `@nestjs/mongoose` to `nestjs-typegoose` but error is still persist

**Comment by KROSF** [comment] 2019-11-01 17:47
@RyannGalea I tried your solution but still not working, typescript complains and throw the following error.
```
A decorator can only decorate a method implementation, not an overload.ts(1249)
```

**Comment by hasezoey** [comment] 2019-11-01 17:54
@KROSF, where does `relayId` get called?

**Comment by hasezoey** [comment] 2019-11-01 18:03
didnt found where it gets called, but it gets called, i tried logging `this`, and why is it not what it supposed to be?

**Comment by KROSF** [comment] 2019-11-01 18:04
@hasezoey, i never call relayId by my self but i think is called when the resolver is preparing the data to response.

**Comment by hasezoey** [comment] 2019-11-01 18:04
like replacing `return this._id` with `return (this as any)._doc._id` fixed it

**Comment by KROSF** [comment] 2019-11-01 18:13
yes, that is the current approach that i using, but when i use class-transformer `this._doc._id`is undefined but `this._id` is defined so my current solution is
```ts
@Field(() => ID, { name: 'id' })
get relayId (): string {
    return this._id || this._doc._id
}
```

**Comment by hasezoey** [comment] 2019-11-01 18:39
It seems like that graphql / nestjs-typegoose do mose things, that should not be done, like this one


Additonal info:
```ts
get relayId(): any {
    console.log('RelayID', this instanceof (mongoose as any).Document, this instanceof User);
    return (this as any)._doc._id;
  }
```
results in
```
RelayID false true // but it should be "true false"
```


@KROSF if you dont know this already, try to upgrade to typescript 3.7 when possible and replace it with `this?._id ?? this._doc._id` (nullish coalescing)

**Comment by hasezoey** [comment] 2019-11-01 19:16
I will let this open because i dont know how this is caused, and why i cant reproduce it in "pure" typegoose - that is why it has "has repro script" & "cant reproduce"

**Comment by KROSF** [comment] 2019-11-01 19:36
@hasezoey thanks for your help i will try to figure out how the method is called.

**Comment by hasezoey** [comment] 2019-11-02 10:32
could reproduce it, thanks to me learning nestjs & class-transfromer
code to reproduce:
```ts
// NodeJS: 12.13.0
// MongoDB: 4.2-bionic (Docker)
import { DocumentType, getModelForClass, prop } from "@typegoose/typegoose"; // @typegoose/typegoose@6.0.4
import { Base } from "@typegoose/typegoose/lib/defaultClasses";
import { classToPlain } from "class-transformer";
import * as mongoose from "mongoose"; // mongoose@5.7.6

class User extends Base /* implements Node */ {
    public get relayId(this: DocumentType<User>): string {
        console.log(this);
        console.log(this instanceof (mongoose as any).Document);
        console.log(this._id); // undefined
        console.log((this as any)._doc._id); // this works
        return this._id; // undefined
    }
}
const UserModel = getModelForClass(User);

(async () => {
    await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verify96", useCreateIndex: true, useUnifiedTopology: true });

    const createdUser = await UserModel.create({});
    console.log(classToPlain(createdUser));
    console.log(createdUser.relayId);

    await mongoose.disconnect();
})();
```

or somewhere in nestjs code `@UseInterceptors(ClassSerializerInterceptor)`

---

but i still dont understand why it happens

**Comment by hasezoey** [comment] 2019-11-02 11:18
i think i found a solution, but for this https://github.com/typestack/class-transformer/issues/227 would need to get implemented

**Comment by hasezoey** [comment] 2019-11-02 11:21
Current solution i found (for nestjs):
```ts
class Intercept implements NestInterceptor {
	public async intercept(
		context: import("@nestjs/common").ExecutionContext,
		next: import("@nestjs/common").CallHandler<any>
	): Promise<any> {
		Logger.log(format("hello from interceptor", ...arguments));

		return next.handle().pipe(map((data) => {
			if (data instanceof (mongoose as any).Document) {
				return data.toJSON({ virtuals: true });
			}

			return classToPlain(data);
		}));
	}
}

@Controller("cats")
@UseInterceptors(Intercept)
export class CatsController { }
```

instead of `@UseInterceptors(ClassSerializerInterceptor)` - they would conflict

**Comment by hasezoey** [comment] 2019-11-02 21:19
Added an "known-issue" in bcfadc9bf5c25726efc91708e62b4e5f4c62ca6c (with a "workaround"), view them at https://typegoose.github.io/typegoose/guides/known-issues/

**Comment by hasezoey** [comment] 2019-11-03 10:59
i'm closing this in favor of #108 

-> if wrongly closed, please comment

**Closed by hasezoey** 2019-11-03 10:59 UTC
Labels: bug, discussion, has repro script, help wanted, info needed

**Comment by Roms1383** [comment] 2020-10-20 02:39
I hope I'm not polluting the discussion with unnecessary comment but I would like to state that `mongoose` method will by default return a mongoose object with tons of extra methods to work on the model, hence why if you want to use it with for example `class-transformer` you indeed have to use `toJSON`, `toObject` or even better IMHO `lean`. Best way would probably be to implement a generic `MongooseSerializerInterceptor` accepting parameters to fine-tune your output (the way you showed it with your `Intercept` class @hasezoey is correct indeed).
