### ISSUE TITLE
updateMany() returns wrong nModified value

### ISSUE THREAD

**Issue by vovarevenko** [typegoose/typegoose#388] opened 2020-09-26 12:32 UTC
## Versions

- NodeJS: 12.18.3
- Typegoose(NPM): 7.4.1
- mongoose: 5.10.7

## What is the Problem?

updateMany().nModified value = the number of documents that are matched rather than changed

## Code Example

```ts
import { getModelForClass, prop } from '@typegoose/typegoose'

class Vendor {
  @prop({ required: true, index: true })
  name: string
}

const VendorModel = getModelForClass(Vendor)

async function start() {
  await VendorModel.create({ name: 'TEST-1' })
  await VendorModel.create({ name: 'TEST-1' })
  await VendorModel.create({ name: 'TEST-2' })

  const result = await VendorModel.updateMany({}, { name: 'TEST-2' })

  console.log(result.n) // 3 (correct value)
  console.log(result.nModified) // 3 (wrong value, should be 2)
}

start()
```

## Do you know *why* it happens?

*No*, but maybe there is a mongoose problem?

**Comment by smolinari** [comment] 2020-09-26 13:23
@vovarevenko - Um, but you aren't filtering on anything. So, all three documents are being overwritten, even the last doc with the same object/ value. Your expectation that the last doc not to be overwritten is incorrect. At least, that seems to be the situation. 😁 

Scott

**Comment by hasezoey** [comment] 2020-09-26 13:38
closing because this isnt an typegoose issue

(and because @smolinari provided an answer on why it is 3)

**Closed by hasezoey** 2020-09-26 13:38 UTC
Labels: bug

**Comment by vovarevenko** [comment] 2020-09-26 15:18
@smolinari, @hasezoey

I disagree. If you're right, both values will always be equal. So, why are there two fields (`n`, `nModified`)?

If I use the mongodb command line like this:
```mongodb
db.vendors.updateMany({}, { $set: { name: 'TEST-2' } })
```
i get this result:
```js
{
  acknowledged: 1,
  insertedId: null,
  matchedCount: 3, // <-- 3 (correct value)
  modifiedCount: 2, // <-- 2 (correct value, but typegoose will return 3)
  upsertedCount: 0,
}
```

Method `updateMany()` should return `n` = _number of **matched** documents_ and `nModified` = _number of **modified** documents_, but now both values equal to number of matched documents.

**Comment by hasezoey** [comment] 2020-09-26 15:52
@vovarevenko im holding out on this conversation because this is not an typegoose problem, because typegoose dosnt modify such functions, you would probably more right in mongoose
(and i never used it this way)

**Comment by smolinari** [comment] 2020-09-26 15:53
>  If you're right, both values will always be equal. So, why are there two fields (n, nModified)?

If you don't filter on anything, then yes, both values should be the same. In your shell method, you are also using `$set`, which changes the behavior.

Scott

**Comment by vovarevenko** [comment] 2020-09-26 16:00
> @vovarevenko im holding out on this conversation because this is not an typegoose problem, because typegoose dosnt modify such functions, you would probably more right in mongoose
> (and i never used it this way)

@hasezoey Now I understand you. I will test this function in mongoose and make a report to the mongoose repository. Thanks.

**Comment by vovarevenko** [comment] 2020-09-26 16:08
> > If you're right, both values will always be equal. So, why are there two fields (n, nModified)?
> 
> If you don't filter on anything, then yes, both values should be the same. In your shell method, you are also using `$set`, which changes the behavior.
> 
> Scott

@smolinari, you are wrong. Provide proof that both fields copy the value of the mongodb `matchedCount` field or that `$set` changes the behavior.

What you are talking about implies that the `updateMany().n` field will always be equal to `updateMany().nModified` field.

The `nModified` field should return the number of **modified** documents, not the number of **matched** documents.

If you think you are right, please provide proof so that I do not create an extra issue in the mongoose package.

**Comment by hasezoey** [comment] 2020-09-26 16:13
https://mongoosejs.com/docs/api.html#model_Model.updateMany

> ```ts
> const res = await Person.updateMany({ name: /Stark$/ }, { isDeleted: true });
> res.n; // Number of documents matched
> res.nModified; // Number of documents modified
> ```

**Comment by smolinari** [comment] 2020-09-26 16:16
> The nModified field should return the number of modified documents, not the number of matched documents.

Yes, and if you don't filter on anything, then ALL documents get modified.

Scott

**Comment by vovarevenko** [comment] 2020-09-26 16:23
> Yes, and if you don't filter on anything, then ALL documents match and thus get modified.

@smolinari, yes. All documents match and this is `n` field. But `nModified` field should return only modified docs count. Please, give me time to report this issue to mongoose and then we'll talk about it. 😄😄😄

**Comment by vovarevenko** [comment] 2020-09-26 16:33
omg..

I tried this code:
```js
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true, useUnifiedTopology: true });

const Cat = mongoose.model('Cat', { name: String });

const kitty_1 = new Cat({ name: 'Zildjian' });
const kitty_2 = new Cat({ name: 'Zildjian' });
const kitty_3 = new Cat({ name: 'John' });

await kitty_1.save();
await kitty_2.save();
await kitty_3.save();

const result = await Cat.updateMany({}, { name: 'John' });

console.log(result.n); // 3 (correct value)
console.log(result.nModified); // 2 (correct value)
```

Both values are correct. So, maybe the problem is in the typogoose? 😄

**Comment by hasezoey** [comment] 2020-09-26 16:44
tested what your code would be equal in typegoose, no problem, all correct values, 3-2

```ts
// NodeJS: 14.10.0
// MongoDB: 4.2-bionic (Docker)
import { getModelForClass, prop } from "@typegoose/typegoose"; // @typegoose/typegoose@7.4.0
import * as mongoose from "mongoose"; // mongoose@5.10.6 @types/mongoose@5.7.36

class Cat {
  @prop()
  public name?: string;
}
const CatModel = getModelForClass(Cat);

(async () => {
  await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verify388", useCreateIndex: true, useUnifiedTopology: true });

  const kitty_1 = await CatModel.create({ name: "Zildjian" });
  const kitty_2 = await CatModel.create({ name: "Zildjian" });
  const kitty_3 = await CatModel.create({ name: "John" });

  const result = await CatModel.updateMany({}, { name: "John" });

  console.log(result.n); // 3 (correct value)
  console.log(result.nModified); // 2 (correct value)

  await mongoose.disconnect();
})();
```

**Comment by vovarevenko** [comment] 2020-09-26 18:28
I found what is the problem.

If we run without a `timestamps` parameter mongoose does this:
```
Mongoose: cats.updateMany({}, { '$set': { name: 'John' } }, {})
```
but if we run with `timestamps: true` parameter mongoose does this:
```
Mongoose: cats.updateMany({}, { '$set': { name: 'John' } }, {})
Mongoose: cats.updateMany({}, {
  '$setOnInsert': { createdAt: new Date("Sat, 26 Sep 2020 17:56:54 GMT") },
  '$set': {
    updatedAt: new Date("Sat, 26 Sep 2020 17:56:54 GMT"),
    name: 'John',
  },
}, {})
```

Even if a `name` field is not modified, `updatedAt` field has been modified and mongodb will update all matched docs.

As a result: updateMany().nModified does not work correctly if `timestamps: true` for model schema.
This can be solved by filtering by non-compliance with the updated field, but this is not correct in my opinion. I already wrote about this above.

Do you think this needs to be fixed at the mongoose level? I think yes. I think this is not intuitive functionality and this does not inherit the `updateMany` logic from mongodb.

Also, I omitted the `timestamp` option in the first example for this issue. So, my first example was incorrect. Sorry.

**Comment by smolinari** [comment] 2020-09-27 08:14
I'm still going stick to what I said, if you don't filter on anything, you can't expect the correct results. The fact that MongoDB happens to ignore replacing values that are the same isn't something you should rely on. Filter for the documents that "must" be altered and you'll be fine and everything, including the Modified By timestamps will work as intended. 

Scott

**Comment by hasezoey** [comment] 2020-09-27 08:26
@smolinari i understand @vovarevenko, the problem it wasnt the right was that there was the hidden "updatedAt" update, which afffected all documents matching the query

**Comment by smolinari** [comment] 2020-09-27 09:49
Yeah. I do understand that. 

But, this is the issue:

> matching the query

The match to an empty object is "everything", because there is no filter. If the normal behavior is to not count a modified document, because the object's values are the same, doesn't stop the fact that the file will still be modified. It gets overwritten. @vovarevenko - is thinking that because the values to be changed are the same, that also the modification shouldn't happen. That is incorrect thinking. The document is also overwritten, just not counted as modified (something I've now learned too).

I'd also even venture to say, this use case is impractical. It's one thing to send an updateMany query with no filter to a collection of 3 documents. It's quite something else, and something to seriously avoid, with a collection of millions, or even thousands of documents. You'd be overwriting them all. That should never happen. Filter on what "must" be changed, then everything works as it should. 

Scott

**Comment by vovarevenko** [comment] 2020-09-27 10:18
> If the normal behavior is to not count a modified document, because the object's values are the same, doesn't stop the fact that the document will still be modified. It gets overwritten.

Give me some proofs please. I didn't know that.

> The document is also overwritten, just not counted as modified (something I've now learned too).

Give me some proofs please. I didn't know that.

**Comment by vovarevenko** [comment] 2020-09-27 11:40
This issue in mongoose rep: https://github.com/Automattic/mongoose/issues/9452
Main issue for this problem: https://github.com/Automattic/mongoose/issues/6861

**Comment by smolinari** [comment] 2020-09-27 12:39
> Give me some proofs please. I didn't know that.

You found the proof yourself. The timestamping of the document shows the document is being written to. I've only deducted, with the findings of hasezoey, that because the value of the document stays the same, it is then not counted as modified. The activity of modification, in your use case's example, is to overwrite what was already there, just not count it as being modified. If anything, that might be considered incorrect, but in the end, it isn't. 

Let me explain this from a different perspective. The object/ value you want set has nothing to do with filtering. I mean, MongoDB isn't looking at your object/ value and saying, "hmmm.... wait a sec. On that last document, I'll ignore modifying it, because, well, it's the exact same thing."

What MongoDB IS thinking is, "Ok. I've been told to filter on nothing, so I must overwrite all documents with the value I've been given. Hmm.. but on this last document, it seems to have the same value, so I'll overwrite it anyway, but won't count it as modified." 

With the Github issues....

That first issue proves my point. MongoDB ignores what is supposed to be updated as compared to what is being updated. It doesn't think, "hmm, the values are exactly the same, so I won't do anything." It DOES overwrite the document/ subdocument THEN looks at the values and says, "hmmm... they were the same, I'll not count it as modified." That user also had timestamping going on, thus still had the modification counted. Same as you have.

I'd say, in that second issue, the user should be doing this:
```
User.update({_id: 1}, foo: {$ne: 'bar'}, {{$addToSet: {foo: 'bar'}}).exec().then(res => {
   console.log(res)
}
```

If `foo` is already set to `bar`, then don't update. That is what you are expecting too right? 

Or in your example, the updateMany should look like this:

```
const result = await VendorModel.updateMany({name: {$ne: 'TEST-2'}, { name: 'TEST-2' })
```

The key is the filter. With no filter, MongoDB will attempt to overwrite everything. It is proper behavior. Your expectation that the value to be changed being the same should stop MongoDB from carrying out the overwrite, is incorrect. If you want that, then you need to filter for it accordingly.  

Scott

**Comment by vovarevenko** [comment] 2020-09-27 13:06
@smolinari, you are constantly trying to explain to me how to count modified documents and explain why it should be done this way. I think this is not the behavior to be expected. Typegoose, Mongoose and MongoDB are working correctly, as we have already found out. But `timestamps` in pre hook from Mongoose makes `n` and `nModified` fields useless.

I do not argue that this behavior is correct now. I just think it makes using `n` and `nModified` fields less intuitive.

I left a comment. Check it out, maybe it will suit you too: https://github.com/Automattic/mongoose/issues/6861#issuecomment-699626231

**Comment by smolinari** [comment] 2020-09-27 13:13
I'm not trying to explain to you how to count modified documents. I'm trying to explain to you that if you don't filter your updateMany query, that all documents will be physically modified. You are expecting that they shouldn't be. 

> Maybe you should separate the targeting update fields and the companion update fields at the mongodb level?

This is the issue. You are expecting MongoDB to do something it isn't designed to do. There are no "targeted update fields". MongoDB just overwrites any and all documents according to how you filter on the documents. No filter, everything is overwritten. 

Scott

**Comment by vovarevenko** [comment] 2020-09-27 13:22
@smolinari, you did not give any proof that the database first updates the document, and then we look to see if there was a change instead of checking whether it needs to be updated before updating. Please, give me some proofs please. If this is true, I can at least understand why you are so persistent.

Also, adding filters is difficult if there are many fields or if there are complex fields from objects or arrays.

To be honest, I don't understand why you think it's wrong to use an update without filters.

I made a test from the example above with 2 million records. The performance difference was only about 10%. Indexes only make things worse, probably because the database has to update them too.

Again, I understand why this behavior occurs and I understand that there is no logical error in this. My position in the created issue (in mongoose rep) is, rather, an improvement in functionality and not a bug report.

Thanks Scott.

**Comment by hasezoey** [comment] 2020-09-27 13:23
@smolinari here the official documentation:
https://docs.mongodb.com/manual/reference/method/db.collection.updateMany/

> **matchedCount**(`n` in mongoose) containing the number of matched documents
> **modifiedCount**(`nModified` in mongoose) containing the number of modified documents

means that `n` is how many documents matched the query, and `nModified` how many got actually changed to the new data

**Comment by vovarevenko** [comment] 2020-09-27 13:32
@hasezoey, we spent too much time on this discussion. I will continue discussion if @smolinari provides proofs that MongoDB is first updating and then checking the document instead of first checking and then updating the document.

**Comment by vovarevenko** [comment] 2020-09-27 13:35
If this is true, then it will be difficult to implement behavior that takes into account non-key fields. But if he is wrong, then I see it as quite feasible to add MongoDB's functionality as I described here and I am ready to create a repository from the repository.

**Comment by smolinari** [comment] 2020-09-27 14:03
> means that n is how many documents matched the query, and nModified how many got actually changed to the new data

Obviously MongoDB is noticing that the document value and the value to be changed are the same and thus, doesn't count that document as being modified, even though the document was overwritten, which is why the pre trigger is fired.

Scott

**Comment by smolinari** [comment] 2020-09-27 14:13
> To be honest, I don't understand why you think it's wrong to use an update without filters.

I didn't say it is wrong. I said, it is wrong to expect MongoDB to not carry out the update (to overwrite) of all the documents, because that is what an updateMany without a filter will do. It will update ALL of the documents. 

Scott

**Comment by vovarevenko** [comment] 2020-09-27 14:21
> It will update ALL of the documents.
Stop writing this. Seriously. I am still waiting for the proofs about this.

**Comment by hasezoey** [comment] 2020-09-27 14:44
@smolinari i dont know if mongodb actually checks first and if not already the same updates, or updates and checking if something changed, things is that `n` is always all documents that matched the query (even if ALL documents), and `nModified` is how many changed the values

**Comment by smolinari** [comment] 2020-09-30 10:48
Ok. I went and had a discussion on the MongoDB forum and you are right. MongoDB doesn't overwrite the data in the documents, when the update data is the same. 

However, it is also clear, that with the Mongoose pre hook and how the Node client works, there is no information available from the updateMany operation to go on, so that Mongoose can properly add the updatedAt timestamps to only those docs that were actually updated. And thus, we are back to my statement. You have to filter on the data you really need updated, for the updatedAt timestamps to work. There isn't anything MongoDB offers to do it differently. 

Scott
