### ISSUE TITLE
Can't fix of ref E005 error

### ISSUE THREAD

**Issue by NitelPhyoe** [typegoose/typegoose#455] opened 2020-12-22 06:59 UTC
## Versions
System: Window 10
node: 14 LTS

## Dependencies
```
"@typegoose/typegoose": "^7.4.5",
"@types/express": "^4.17.9",
"@types/mongoose": "^5.10.3",
"@types/node": "^14.14.14",
"express": "^4.17.1",
"mongoose": "5.10.18",
"ts-node-dev": "^1.1.1",
"typescript": "^4.1.3"
```

## What is the Problem?

i use `{ ref: () => Class }` described in doc but this don't work still E005

the following is reproduce error of E005 

[test.zip](https://github.com/typegoose/typegoose/files/5728260/test.zip)

**Comment by hasezoey** [comment] 2020-12-22 12:08
simple reason: Circular Imports (A uses B, B uses A), only one of them exists for one of them, so it will be undefined
the only fix is to manually put in the name as an string (this is an JS problem, nothing that typegoose can fix without extensive caching)

**Comment by hasezoey** [comment] 2020-12-22 12:09
this is more or less an duplicate of #93

**Comment by realvikas** [comment] 2021-01-10 14:42
I am also facing this, using ref function and no circular imports.

**Comment by hasezoey** [comment] 2021-01-10 15:37
@realvikas could you post your code?

**Comment by hasezoey** [comment] 2021-05-29 11:42
closing because stale

---

For anyone searching for this, the easiest fix is to use `ref: () => Class` typing and putting all `getModelForClass` calls (if used) into one file, classes can stay in their own files

**Closed by hasezoey** 2021-05-29 11:42 UTC
Labels: bug
