### ISSUE TITLE
ReOpen: "Strange behaviour when referencing 'model.modelName'"

### ISSUE THREAD

**Issue by LucioMF** [typegoose/typegoose#186] opened 2020-01-30 17:43 UTC
## Versions

- NodeJS: 10.15.3
- Typegoose(NPM): 6.2.2
- mongoose: 5.8.10
- mongodb: 4.2.1
- nestjs / nestjs-typegoose: 6.11.4 / 7.0.0

## What is the Problem?

I'm posting this issue again due to was closed before I could test the answers provided. And neither of the answers work. See [this](https://github.com/typegoose/typegoose/issues/184).
I recently upgrade to version 6.
I was using the "modelName" property of the model, to tag my endpoints in Swagger. But with the new version this seems to somehow interfere with the queries (of any kind) to the database. They stay frozen and never respond.
It only works when, in one way or another, I give the hardocode string to swagger.
It's weird because when I refer to model.modelName, swagger does work, and I can see the name of the model in the tag entering localhost: 8080/api/docs. But it makes all mongo queries freeze

## Code Example

Base Model:

```ts
import { prop, modelOptions } from '@typegoose/typegoose';

@modelOptions({
    schemaOptions: {
        toJSON: {
            virtuals: true,
            getters: true,
        },
        toObject: {
            virtuals: true,
            getters: true,
        },
    },
})
export class BaseModel<T> {
    @prop({ default: Date.now() })
    createdAt?: Date;

    @prop({ default: Date.now() })
    updatedAt?: Date;

    id?: string;
}
```

User Model:
```ts
import { BaseModel } from '../../shared/base.model';
import { prop, ReturnModelType, Ref, arrayProp, getModelForClass } from '@typegoose/typegoose';

export class User extends BaseModel<User> {
    @prop({ lowercase: true, trim: true, required: [true, 'username is required'], minlength: [4, 'Must be at least 4 characters'], unique: true })
    username!: string;

    @prop({ required: [true, 'password is required'], minlength: [6, 'Must be at least 6 characters'] })
    password!: string;

    @prop()
    firstName?: string;

    @prop()
    lastName?: string;

    get fullName(): string {
        return `${this.firstName} ${this.lastName}`;
    }

    static get model(): ReturnModelType<typeof User> {
        /* old version way */
        // return new User().getModelForClass(User);
        return getModelForClass(User);
    }

    static get modelName(): string {
        /* If I put a breakpoint here I can see that the model does have the modelName property,
            and that has the expected valueo */
        return this.model.modelName;

       /* If I return it like follow it works perfectly */
       // return 'User';
    }
}
```

User service:
```ts
import {
    Injectable,
} from '@nestjs/common';
import { InjectModel } from 'nestjs-typegoose';
import { User } from './models/user.model';
import { ReturnModelType } from '@typegoose/typegoose';

@Injectable()
export class UserService {
    protected model;
    constructor(
        @InjectModel(User) userModel: ReturnModelType<typeof User>,
    ) {
        this.model = userModel;
    }

    async findAll(filter = {}): Promise<DocumentType<User>[]> {
        return this.model.find(filter).exec();
    }

}
```
User Controller:
```ts
import {
    Controller,
    HttpStatus,
    Res,
    Get,
} from '@nestjs/common';
import { UserService } from './user.service';
import { ApiTags, ApiResponse } from '@nestjs/swagger';
import { User } from './models/user.model';

@Controller('user')
@ApiTags(User.modelName) /* Here I use it */
export class UserController {
    constructor(
        private readonly userService: UserService,
    ) {  }

    @Get('/listusers')
    @ApiResponse({ status: HttpStatus.OK, type: String })
    @ApiResponse({ status: HttpStatus.BAD_REQUEST })
    async listAllUsers(
        @Res() res,
    ) {
        const users = await this.userService.findAll();
        return res.send(users);
    }
}
```

## Steps to reproduce
Run the code above (or some similar) and call ''listusers" method. It will get frozen in the findAll query.
Now replace the line `return this.model.modelName;` in the virtual get property of the model by `return 'User';` and it will work.

## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment] 2020-01-30 17:53
Duplicate of #184

Please dont open a new issue, you can just reopen the closed one

**Closed by hasezoey** 2020-01-30 17:53 UTC
Labels: bug
