### ISSUE TITLE
Add isRef typeguard

### ISSUE THREAD

**Issue by camo-f** [typegoose/typegoose#193] opened 2020-02-07 13:05 UTC
Hi there,

## Describe what you need | want

Given the following classes :
```
class Nested {}

class Parent {
  @prop({ ref: "Nested" })
  public nest: Ref<Nested>;
}
```
It would be useful to be able to compare nest reference (most of the time _id) without populating nest. It avoids an unnecessary query to the database.
I didn't find a way to solve this, as Typescript returns the following error :

> Argument of type 'Ref<Nested, ObjectId>' is not assignable to parameter of type 'string | number | ObjectId'.

## Do you have already an idea for the implementation?

A naive implementation would be adding a typeguard named `isRef` using the existing `isDocument` typeguard :
```
export function isRef<T, S extends RefType>(doc: Ref<T, S>): doc is S {
  return !isDocument(doc);
}
```

I got it to work in a simple example with `Types.ObjectId` as `RefType`. I guess it would need further testing but I preferred to expose the idea first.
We could also add a typeguard `isRefArray` similar to `isDocumentArray`.

**Comment by hasezoey** [comment] 2020-02-07 17:39
why not just use `isDocument`(/`isDocumentArray`)? this is what they were intended for, References (and general checking if it is an document)

**Comment by camo-f** [comment] 2020-02-07 21:43
`isDocument` is giving the type of the referenced object, but I need `refType` (mainly ObjectId, but it could be string, number or buffer), which I can't get since `isDocument` is only giving `Document<T>` (see https://github.com/typegoose/typegoose/blob/master/src/typeguards.ts#L10)

Here is an example : Typescript considers the following as invalid because parent.nest is typed as `Ref<Nested, ObjectId>`. `isDocument` gives `Nested`, but I can't get `ObjectId` for `parent.nest`.
```
const parent = ... // retrieve from database without populate
const id = new Types.ObjectId('hexstring');
if (id === parent.nest) {
 // Same id
}
```

**Comment by hasezoey** [comment] 2020-02-07 21:58
```ts
const doc = await SomeModel.find().exec();
const tocheck = new Types.ObjectId('SomeHexString')
if (isDocument(doc.nested)) {
  // it is already populated
  if (doc.nested._id.equals(tocheck)) {
    // equals tocheck
  } else {
    // dosnt equal tocheck
  }
} else {
  if (doc.nested.equals(id)) { // you can just assume it is an ObjectId, because you defined it as such
    // equals tocheck and is NOT Populated
  } else {
   // dosnt equal tocheck and is NOT Populated 
  } 
}
```

otherwise, if you use discriminated models (that somehow have something like ObjectId id's and string id's, then do the following

```ts
// assume not populated path
if (doc.nested instanceof ObjectId) {
  if (doc.nested.equals(tocheck)) {
    // is not populated, equals the id, and is an ObjectId
  } else {
    // is not populated, dosnt equals the id, but is an ObjectId
  }
} else if (typeof doc.nested === "string") {
  if (doc.nested === tocheck) // assume tocheck is an string
    // is not populated, equals tocheck, and is an string
  } else {
    // is not populated, dosnt equal tocheck, but is an string
  }
}
```

PS: you can do the second way if you are in strict mode and need more strict types, but the first way should work if you have types your `_id` (like using the `Base` class)

**Comment by camo-f** [comment] 2020-02-10 12:18
Ref is a generic type, and `instanceof` operator is not supported for those.
For a ref field, Typescript shows `Ref<Parent, RefType>`, except when using `isDocument` which narrows the type to `DocumentType<Parent>`.
Why do you think Typegoose should not provide this typeguard ?

**Comment by hasezoey** [comment] 2020-02-10 19:26
@camo-f because it could be any custom type, it is hard to implement - any suggestions?

>  and instanceof operator is not supported for those.

what do you mean that `instanceof` is not supported for RefType?

---

and when you are not using discriminated models with differing identification types, it is easy to implement yourself, just an easy if check of the type (depending on which type it is) [examples in this comment](https://github.com/typegoose/typegoose/issues/193#issuecomment-583633690)

**Comment by camo-f** [comment] 2020-02-11 08:46
Well, not that hard if it uses a generic type :
```
export function isRef<T, S extends RefType>(doc: Ref<T, S>): doc is S {
  return !isDocument(doc);
}
```
Here I used the same definition used for `isDocument`, where `S` is the RefType.
Moreover, isn't RefType limited to string, number, Buffer and ObjectId ? In that case, it should be easy to test any of them.
We can also use RefType directly, it might be safer :
```
export function isRef<T, S extends RefType>(doc: Ref<T, S>): doc is S {
  return doc instanceof RefType;
}
```
Both implementations are working on a simple example with ObjectId.
The important part here is `doc is S`, which allows Typescript to narrow RefType to the correct type.

I tried your examples with the following implementations (given that RefType is `ObjectId`) :
```
if (isDocument(parent.nested)) {
 // type is Nested, I can access property of the class
} else {
  // type should be ObjectId but Typescript rejects it
  console.log(parent.nested.toHexString());
}
```
and
```
if (parent.nested instanceof Types.ObjectId) {
  // type should be ObjectId but Typescript rejects it
  console.log(parent.nested.toHexString());
} else {
  // type is Nested
}
```
In both cases, I get :
> Property 'toHexString' does not exist on type 'Ref<Nested, ObjectId>'.
>   Property 'toHexString' does not exist on type 'Nested'
Or did I miss something ?

**Comment by hasezoey** [comment] 2020-02-11 18:45
> Or did I miss something ?

`Property 'toHexString' does not exist on type 'Ref<Nested, ObjectId>'.` is this an compile-time error? when yes, did you already try to `ts-ignore` it and test again?

---

to your first example:
this would mean if the value is `undefined` it would still be set to the RefType, which would be wrong
to your second example:
this is very verbose and not extendable...

**Comment by camo-f** [comment] 2020-02-12 09:10
It is indeed a compile-time error, it works with a `ts-ignore` comment. Though I don't think it's a good practice to use these comments, one of Typescript purposes being type errors prevention.
* * *
Then adding a test `doc !== undefined` should solve this problem. Moreover it gives the possibility to change RefType easily, even if it's quite a rare use-case.
```
export function isRef<T, S extends RefType>(doc: Ref<T, S>): doc is S {
  return doc !== undefined && !isDocument(doc);
}
```

**Comment by hasezoey** [comment] 2020-02-12 20:44
this will be in the next version 6.3.3 / 6.4 (depending on what comes first)

**Closed** 2020-02-12 20:43 UTC
Labels: feature

**Comment by camo-f** [comment] 2020-02-13 08:47
I can make a PR for this if you want

**Comment by hasezoey** [comment] 2020-02-13 13:44
@camo-f for what? it already included in the next version

**Comment by camo-f** [comment] 2020-02-13 16:12
I didn't see you already committed the feature, so I assumed you may have needed help for it. Thanks a lot, great job !

**Comment by andreialecu** [comment] 2020-05-03 16:53
What's a quick way of getting the ref `_id`?

Seems that I need to write the following every time:

```
    const refId = isRefType(model.theRef)
      ? model.theRef
      : model.theRef._id;
```

Unless I'm missing something obvious, perhaps an utility method could be added to the library, something like `getRefId(model.theRef)`.

```
export function getRefId<T extends { _id: any }, S extends RefType>(
  doc: Ref<T, S>,
) {
  return isRefType(doc) ? doc : (doc._id as S);
}
```

**Comment by hasezoey** [comment] 2020-05-03 17:09
@andreialecu this is an already closed and finished issue, next time please open a new issue or ask in the discord server

---

when you `_id` type is an ObjectId, then i think `doc.ref._id` is always allowed
but if it is something different, like of type string, then yes, it is probably needed

-> and no, this is note within scope of this project

**Comment by andreialecu** [comment] 2020-05-03 17:16
No, `doc.ref._id` is not allowed under any circumstance, I wouldn't have commented otherwise. At least not in typescript strict mode, I haven't tested without.

The only way to get the `_id` is via the code I posted above. At least you confirmed I wasn't missing something obvious.

The comment might help someone.

**Comment by hasezoey** [comment] 2020-05-03 17:18
@andreialecu i think in normal js it is allowed (/ not in the typescript types), but the right way would be to use some function like you provided

**Comment by andreialecu** [comment] 2020-05-03 18:09
It only works for `ObjectId` because mongoose adds an `_id` to ObjectId instances: https://mongoosejs.com/docs/populate.html#checking-populated. The types for mongoose don't include it unfortunately. I guess it's an issue with `@types/mongoose`.
