### ISSUE TITLE
Array Methods

### ISSUE THREAD

**Issue by Negan1911** [typegoose/typegoose#255] opened 2020-05-12 01:28 UTC
## Which feature

- [`MongooseArray` Methods](https://mongoosejs.com/docs/api/array.html)
- [`DocumentArray` Methods](https://mongoosejs.com/docs/subdocs.html#finding-a-subdocument)

## Why do you want it
It is useful for work with sub-document arrays to have methods like `.create` or `.id`

## Additional Notes
Made a test and the methods are there still available on the components, just not exported by typescript, if someone has some guidance on how that could be implemented I could give it a try!

**Comment by hasezoey** [comment] 2020-05-12 11:36
if you want to use these functions, you have to define the arrays with them, here an example:

```ts
// NodeJS: 12.16.2
// MongoDB: 4.2-bionic (Docker)
import { getModelForClass, prop, arrayProp, DocumentType } from "@typegoose/typegoose"; // @typegoose/typegoose@7.0.0
import * as mongoose from "mongoose"; // mongoose@5.9.10

class Nested {
  @prop({ required: true })
  public someprop!: string;
}

class Parent {
  @arrayProp({ items: String })
  public normalArray!: mongoose.Types.Array<string>;

  @arrayProp({ items: Nested })
  public documentArray!: mongoose.Types.DocumentArray<DocumentType<Nested>>;
}
const ParentModel = getModelForClass(Parent);

(async () => {
  await mongoose.connect(`mongodb://localhost:27017/`, { useNewUrlParser: true, dbName: "verify255", useCreateIndex: true, useUnifiedTopology: true });

  const doc = await ParentModel.create({ normalArray: ["hi", "Hello"], documentArray: [{ someprop: "Hello" }, { someprop: "hi" }] });

  console.log(doc);
  doc.documentArray.create({ someprop: "Another hello" });
  doc.normalArray.$pop();
  await doc.save();
  console.log(doc);

  await mongoose.disconnect();
})();
```

**Comment by Negan1911** [comment] 2020-05-12 13:59
That worked great! quick question, do you think that would make sense to add a custom type on typegoose on charge of that, so you could use it as.

```ts
class Parent {
  @arrayProp({ items: String })
  public normalArray!: DocumentArray<string>; // If primitive, will infer mongoose.Types.Array<string>

  @arrayProp({ items: Nested })
  public documentArray!: DocumentArray<Nested>; // If class, will infer mongoose.Types.DocumentArray<DocumentType<Nested>>
}
```

I think that would be a neat addition, and I could try to work on it!

**Comment by hasezoey** [comment] 2020-05-12 14:30
sorry, but this could lead to problems, like custom types

---

i think the issue is solved, closing it

**Closed by hasezoey** 2020-05-12 14:30 UTC
Labels: question

**Comment by Negan1911** [comment] 2020-05-12 14:44
Sure, thanks for your time on this!

**Comment by Negan1911** [comment] 2020-05-21 02:25
At first I thought that this was working fine, but once deployed I started seeing some issues, looks like the metadata is not recognizing `mongoose.Types.DocumentArray` as an array, because I get:
```
WARN You might not want to use option "items" for an non-array @prop type (Account.branches)
WARN Implicitly setting "Mixed" is not allowed! (Account, branches)
INFO	TypeError: this.branches.id is not a function
```

Where my code is
```ts
class Account {
  @prop({ default: '' })
  name: string

  @arrayProp({ items: Branch, default: [] })
  branches: mongoose.Types.DocumentArray<DocumentType<Branch>>

```

**Comment by hasezoey** [comment] 2020-05-21 07:11
@Negan1911 thanks for reporting, will be fixed in next version, for now you can overwrite it `@prop({}, WhatIsIt.Array)`

**Comment by Negan1911** [comment] 2020-05-22 02:34
@hasezoey Before you publish that fix, I've applied your commit using `patch-package` on the `lib/props.js` file, and got this error:

```
{
    "errorType": "ObjectExpectedError",
    "errorMessage": "Tried to set nested object field `branches` to array `` and strict mode is set to throw.",
    "message": "Tried to set nested object field `branches` to array `` and strict mode is set to throw.",
    "name": "ObjectExpectedError",
    "path": "branches",
    "stack": [
        "ObjectExpectedError: Tried to set nested object field `branches` to array `` and strict mode is set to throw.",
        "    at new ObjectExpectedError (/var/task/node_modules/mongoose/lib/error/objectExpected.js:24:11)",
        "    at SingleNestedPath.cast (/var/task/node_modules/mongoose/lib/schema/SingleNestedPath.js:156:11)",
        "    at SingleNestedPath.SchemaType.applySetters (/var/task/node_modules/mongoose/lib/schematype.js:1031:12)",
        "    at SingleNestedPath.SchemaType.getDefault (/var/task/node_modules/mongoose/lib/schematype.js:968:25)",
        "    at $__applyDefaults (/var/task/node_modules/mongoose/lib/document.js:405:22)",
```

That is because how mongoose schema types are being interpreted, I think that for subdocuments typegoose is assigning the `type` and not `[type]`.
I had been trying to track where does that happens but cannot found it.

**Comment by hasezoey** [comment] 2020-05-22 03:08
@Negan1911 currently its always surround as long as `whatis` is set to `WhatIsIt.Array`, this error seems to try to set "undefined/null" to property "branches" of some class

**Comment by Negan1911** [comment] 2020-05-22 03:33
If I apply `@prop({}, WhatIsIt.Array)` I get:
```
console.warn
    You might not want to use option "items" for an non-array @prop type (Account.branches)
```

I'm guessing but WhatIsIt.ARRAY is `0` and maybe is not being [caught on this line](https://github.com/typegoose/typegoose/blob/master/src/prop.ts#L387)?
(Since `WhatIsIt.ARRAY` equals `0` also equals `false`).

Replacing `if (!kind)` with `if (kind === null || kind === undefined)` fixes this issue.

I'm, still looking why when I apply the patch I get that error, which doesn't happen on any other case (it also doesn't happen on jest). Guessing maybe ts-loader is going nuts or something else, will let you know if I found anything useful

**Comment by hasezoey** [comment] 2020-05-22 09:19
@Negan1911 thanks, this was really an problem - didnt notice

**Comment by Volcano-Yang** [comment] 2022-08-26 06:27
thank you very much for your solution to my problem。

**Comment by Solomon-encumbrance** [comment] 2025-02-06 17:09
@hasezoey https://nodeer.space/questions/updating-arrays-with-arrayfilters-in-nested-structures

**Comment by hasezoey** [comment] 2025-02-06 21:32
@Solomon-encumbrance This link is not relevant to this issue.
