### ISSUE TITLE
the latest mongoose package comes with types

### ISSUE THREAD

**Issue by wz930206** [typegoose/typegoose#491] opened 2021-02-19 03:18 UTC
## Versions

- System: windows  
- NodeJS: 12.16.2
- Typescript: 4.0.5

- Compiler / Transpiler: tsc / ts-node / ts-jest 
- Typegoose(NPM): 7.4.8 
- Typegoose(GIT): commithash
- mongoose: 5.11.17 
- @nestjs/cli  7.5.1

## What is the Problem?

node_modules/@types/mongoose/index.d.ts:3559:77 - error TS2314: Generic type 'Query<ResultType, DocType>' requires 2 type argument(s).

3559       callback?: (err: any, doc: DocumentDefinition<T>, res: any) => void): Query<DocumentDefinition<T>> & QueryHelpers;

## Code Example

```ts
code here
```

## Do you know *why* it happens?

npm i -D @types/mongoose

---

**Comment by hasezoey** [comment] 2021-02-19 06:31
Duplicate of #432

**Closed by hasezoey** 2021-02-19 06:31 UTC
Labels: bug
